// This file is auto-generated by @hey-api/openapi-ts

/**
 * AllDebridModel
 */
export type AllDebridModel = {
    /**
     * Enabled
     */
    enabled?: boolean;
    /**
     * Api Key
     */
    api_key?: string;
};

/**
 * AppModel
 */
export type AppModel = {
    /**
     * Version
     */
    version?: string;
    /**
     * Api Key
     */
    api_key?: string;
    /**
     * Debug
     */
    debug?: 'TRACE' | 'DEBUG' | 'INFO' | 'WARNING' | 'ERROR' | 'CRITICAL';
    /**
     * Tracemalloc
     */
    tracemalloc?: boolean;
    filesystem?: FilesystemModel;
    updaters?: UpdatersModel;
    downloaders?: DownloadersModel;
    content?: ContentModel;
    scraping?: ScraperModel;
    ranking?: RtnSettingsModel;
    indexer?: IndexerModel;
    database?: DatabaseModel;
    notifications?: NotificationsModel;
    post_processing?: PostProcessing;
};

/**
 * AudioRankModel
 * Ranking configuration for audio attributes.
 */
export type AudioRankModel = {
    aac?: CustomRank;
    atmos?: CustomRank;
    dolby_digital?: CustomRank;
    dolby_digital_plus?: CustomRank;
    dts_lossy?: CustomRank;
    dts_lossless?: CustomRank;
    flac?: CustomRank;
    mono?: CustomRank;
    mp3?: CustomRank;
    stereo?: CustomRank;
    surround?: CustomRank;
    truehd?: CustomRank;
};

/**
 * CalendarResponse
 */
export type CalendarResponse = {
    /**
     * Data
     */
    data: {
        [key: string]: unknown;
    };
};

/**
 * CometConfig
 */
export type CometConfig = {
    /**
     * Enabled
     */
    enabled?: boolean;
    /**
     * Url
     */
    url?: string;
    /**
     * Timeout
     */
    timeout?: number;
    /**
     * Ratelimit
     */
    ratelimit?: boolean;
};

/**
 * Container
 * Root model for container mapping file IDs to file information.
 *
 * Example:
 * {
 * "4": {
 * "filename": "show.s01e01.mkv",
 * "filesize": 30791392598
 * },
 * "5": {
 * "filename": "show.s01e02.mkv",
 * "filesize": 25573181861
 * }
 * }
 */
export type Container = {
    [key: string]: DebridFile;
};

/**
 * ContentModel
 */
export type ContentModel = {
    overseerr?: OverseerrModel;
    plex_watchlist?: PlexWatchlistModel;
    mdblist?: MdblistModel;
    listrr?: ListrrModel;
    trakt?: TraktModel;
};

/**
 * CustomRank
 * Custom Ranks used in SettingsModel.
 */
export type CustomRank = {
    /**
     * Fetch
     */
    fetch?: boolean;
    /**
     * Use Custom Rank
     */
    use_custom_rank?: boolean;
    /**
     * Rank
     */
    rank?: number;
};

/**
 * CustomRanksConfig
 * Configuration for custom ranks.
 */
export type CustomRanksConfig = {
    quality?: QualityRankModel;
    rips?: RipsRankModel;
    hdr?: HdrRankModel;
    audio?: AudioRankModel;
    extras?: ExtrasRankModel;
    trash?: TrashRankModel;
};

/**
 * DatabaseModel
 */
export type DatabaseModel = {
    /**
     * Host
     */
    host?: string;
};

/**
 * DebridFile
 * Represents a file from a debrid service
 */
export type DebridFile = {
    /**
     * File Id
     */
    file_id?: number | null;
    /**
     * Filename
     */
    filename?: string | null;
    /**
     * Filesize
     */
    filesize?: number | null;
    /**
     * Download Url
     */
    download_url?: string | null;
};

/**
 * DownloadersModel
 */
export type DownloadersModel = {
    /**
     * Video Extensions
     */
    video_extensions?: Array<string>;
    /**
     * Movie Filesize Mb Min
     */
    movie_filesize_mb_min?: number;
    /**
     * Movie Filesize Mb Max
     */
    movie_filesize_mb_max?: number;
    /**
     * Episode Filesize Mb Min
     */
    episode_filesize_mb_min?: number;
    /**
     * Episode Filesize Mb Max
     */
    episode_filesize_mb_max?: number;
    /**
     * Proxy Url
     */
    proxy_url?: string;
    real_debrid?: RealDebridModel;
    all_debrid?: AllDebridModel;
    torbox?: TorBoxModel;
};

/**
 * EmbyLibraryModel
 */
export type EmbyLibraryModel = {
    /**
     * Enabled
     */
    enabled?: boolean;
    /**
     * Api Key
     */
    api_key?: string;
    /**
     * Url
     */
    url?: string;
};

/**
 * ExtrasRankModel
 * Ranking configuration for extras attributes.
 */
export type ExtrasRankModel = {
    '3d'?: CustomRank;
    converted?: CustomRank;
    documentary?: CustomRank;
    dubbed?: CustomRank;
    edition?: CustomRank;
    hardcoded?: CustomRank;
    network?: CustomRank;
    proper?: CustomRank;
    repack?: CustomRank;
    retail?: CustomRank;
    site?: CustomRank;
    subbed?: CustomRank;
    upscaled?: CustomRank;
    scene?: CustomRank;
    uncensored?: CustomRank;
};

/**
 * FfprobeResponse
 */
export type FfprobeResponse = {
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data: {
        [key: string]: unknown;
    };
};

/**
 * FilesystemModel
 */
export type FilesystemModel = {
    /**
     * Mount Path
     */
    mount_path?: string;
    /**
     * Debug Fuse
     */
    debug_fuse?: boolean;
    /**
     * Separate Anime Dirs
     */
    separate_anime_dirs?: boolean;
    /**
     * Vfs Cache Dir
     */
    vfs_cache_dir?: string;
    /**
     * Vfs Cache Max Size Mb
     */
    vfs_cache_max_size_mb?: number;
    /**
     * Vfs Cache Ttl Seconds
     */
    vfs_cache_ttl_seconds?: number;
    /**
     * Vfs Cache Eviction
     */
    vfs_cache_eviction?: string;
    /**
     * Vfs Cache Metrics
     */
    vfs_cache_metrics?: boolean;
    /**
     * Vfs Chunk Mb
     */
    vfs_chunk_mb?: number;
    /**
     * Fetch Ahead Size Mb
     */
    fetch_ahead_size_mb?: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HdrRankModel
 * Ranking configuration for HDR attributes.
 */
export type HdrRankModel = {
    bit10?: CustomRank;
    dolby_vision?: CustomRank;
    hdr?: CustomRank;
    hdr10plus?: CustomRank;
    sdr?: CustomRank;
};

/**
 * IndexerModel
 */
export type IndexerModel = {
    /**
     * Update Interval
     */
    update_interval?: number;
};

/**
 * ItemsResponse
 */
export type ItemsResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Items
     */
    items: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Page
     */
    page: number;
    /**
     * Limit
     */
    limit: number;
    /**
     * Total Items
     */
    total_items: number;
    /**
     * Total Pages
     */
    total_pages: number;
};

/**
 * JackettConfig
 */
export type JackettConfig = {
    /**
     * Enabled
     */
    enabled?: boolean;
    /**
     * Url
     */
    url?: string;
    /**
     * Api Key
     */
    api_key?: string;
    /**
     * Timeout
     */
    timeout?: number;
    /**
     * Ratelimit
     */
    ratelimit?: boolean;
};

/**
 * JellyfinLibraryModel
 */
export type JellyfinLibraryModel = {
    /**
     * Enabled
     */
    enabled?: boolean;
    /**
     * Api Key
     */
    api_key?: string;
    /**
     * Url
     */
    url?: string;
};

/**
 * LanguagesConfig
 * Configuration for which languages are enabled.
 */
export type LanguagesConfig = {
    /**
     * Required
     */
    required?: Array<string>;
    /**
     * Exclude
     */
    exclude?: Array<string>;
    /**
     * Preferred
     */
    preferred?: Array<string>;
};

/**
 * ListrrModel
 */
export type ListrrModel = {
    /**
     * Update Interval
     */
    update_interval?: number;
    /**
     * Enabled
     */
    enabled?: boolean;
    /**
     * Movie Lists
     */
    movie_lists?: Array<string>;
    /**
     * Show Lists
     */
    show_lists?: Array<string>;
    /**
     * Api Key
     */
    api_key?: string;
};

/**
 * LogsResponse
 */
export type LogsResponse = {
    /**
     * Logs
     */
    logs: Array<string>;
};

/**
 * MdblistModel
 */
export type MdblistModel = {
    /**
     * Update Interval
     */
    update_interval?: number;
    /**
     * Enabled
     */
    enabled?: boolean;
    /**
     * Api Key
     */
    api_key?: string;
    /**
     * Lists
     */
    lists?: Array<string | number>;
};

/**
 * MediafusionConfig
 */
export type MediafusionConfig = {
    /**
     * Enabled
     */
    enabled?: boolean;
    /**
     * Url
     */
    url?: string;
    /**
     * Timeout
     */
    timeout?: number;
    /**
     * Ratelimit
     */
    ratelimit?: boolean;
};

/**
 * MessageResponse
 */
export type MessageResponse = {
    /**
     * Message
     */
    message: string;
    /**
     * Tmdb Ids
     */
    tmdb_ids?: Array<string>;
    /**
     * Tvdb Ids
     */
    tvdb_ids?: Array<string>;
};

/**
 * MountResponse
 */
export type MountResponse = {
    /**
     * Files
     */
    files: {
        [key: string]: string;
    };
};

/**
 * NotificationsModel
 */
export type NotificationsModel = {
    /**
     * Enabled
     */
    enabled?: boolean;
    /**
     * On Item Type
     */
    on_item_type?: Array<string>;
    /**
     * Service Urls
     */
    service_urls?: Array<string>;
};

/**
 * OptionsConfig
 * Configuration for various options.
 */
export type OptionsConfig = {
    /**
     * Title Similarity
     */
    title_similarity?: number;
    /**
     * Remove All Trash
     */
    remove_all_trash?: boolean;
    /**
     * Remove Ranks Under
     */
    remove_ranks_under?: number;
    /**
     * Remove Unknown Languages
     */
    remove_unknown_languages?: boolean;
    /**
     * Allow English In Languages
     */
    allow_english_in_languages?: boolean;
    /**
     * Enable Fetch Speed Mode
     */
    enable_fetch_speed_mode?: boolean;
    /**
     * Remove Adult Content
     */
    remove_adult_content?: boolean;
};

/**
 * OrionoidConfig
 */
export type OrionoidConfig = {
    /**
     * Enabled
     */
    enabled?: boolean;
    /**
     * Api Key
     */
    api_key?: string;
    /**
     * Cached Results Only
     */
    cached_results_only?: boolean;
    /**
     * Parameters
     */
    parameters?: {
        [key: string]: unknown;
    };
    /**
     * Timeout
     */
    timeout?: number;
    /**
     * Ratelimit
     */
    ratelimit?: boolean;
};

/**
 * OverseerrModel
 */
export type OverseerrModel = {
    /**
     * Update Interval
     */
    update_interval?: number;
    /**
     * Enabled
     */
    enabled?: boolean;
    /**
     * Url
     */
    url?: string;
    /**
     * Api Key
     */
    api_key?: string;
    /**
     * Use Webhook
     */
    use_webhook?: boolean;
};

/**
 * ParseTorrentTitleResponse
 */
export type ParseTorrentTitleResponse = {
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * ParsedData
 * Parsed data model for a torrent title.
 */
export type ParsedData = {
    /**
     * Raw Title
     */
    raw_title: string;
    /**
     * Parsed Title
     */
    parsed_title?: string;
    /**
     * Normalized Title
     */
    normalized_title?: string;
    /**
     * Trash
     */
    trash?: boolean;
    /**
     * Adult
     */
    adult?: boolean;
    /**
     * Year
     */
    year?: number | null;
    /**
     * Resolution
     */
    resolution?: string;
    /**
     * Seasons
     */
    seasons?: Array<number>;
    /**
     * Episodes
     */
    episodes?: Array<number>;
    /**
     * Complete
     */
    complete?: boolean;
    /**
     * Volumes
     */
    volumes?: Array<number>;
    /**
     * Languages
     */
    languages?: Array<string>;
    /**
     * Quality
     */
    quality?: string | null;
    /**
     * Hdr
     */
    hdr?: Array<string>;
    /**
     * Codec
     */
    codec?: string | null;
    /**
     * Audio
     */
    audio?: Array<string>;
    /**
     * Channels
     */
    channels?: Array<string>;
    /**
     * Dubbed
     */
    dubbed?: boolean;
    /**
     * Subbed
     */
    subbed?: boolean;
    /**
     * Date
     */
    date?: string | null;
    /**
     * Group
     */
    group?: string | null;
    /**
     * Edition
     */
    edition?: string | null;
    /**
     * Bit Depth
     */
    bit_depth?: string | null;
    /**
     * Bitrate
     */
    bitrate?: string | null;
    /**
     * Network
     */
    network?: string | null;
    /**
     * Extended
     */
    extended?: boolean;
    /**
     * Converted
     */
    converted?: boolean;
    /**
     * Hardcoded
     */
    hardcoded?: boolean;
    /**
     * Region
     */
    region?: string | null;
    /**
     * Ppv
     */
    ppv?: boolean;
    /**
     * Site
     */
    site?: string | null;
    /**
     * Size
     */
    size?: string | null;
    /**
     * Proper
     */
    proper?: boolean;
    /**
     * Repack
     */
    repack?: boolean;
    /**
     * Retail
     */
    retail?: boolean;
    /**
     * Upscaled
     */
    upscaled?: boolean;
    /**
     * Remastered
     */
    remastered?: boolean;
    /**
     * Unrated
     */
    unrated?: boolean;
    /**
     * Uncensored
     */
    uncensored?: boolean;
    /**
     * Documentary
     */
    documentary?: boolean;
    /**
     * Commentary
     */
    commentary?: boolean;
    /**
     * Episode Code
     */
    episode_code?: string | null;
    /**
     * Country
     */
    country?: string | null;
    /**
     * Container
     */
    container?: string | null;
    /**
     * Extension
     */
    extension?: string | null;
    /**
     * Extras
     */
    extras?: Array<string>;
    /**
     * Torrent
     */
    torrent?: boolean;
    /**
     * Scene
     */
    scene?: boolean;
};

/**
 * PauseResponse
 */
export type PauseResponse = {
    /**
     * Message
     */
    message: string;
    /**
     * Ids
     */
    ids: Array<number>;
};

/**
 * PlexLibraryModel
 */
export type PlexLibraryModel = {
    /**
     * Enabled
     */
    enabled?: boolean;
    /**
     * Token
     */
    token?: string;
    /**
     * Url
     */
    url?: string;
};

/**
 * PlexWatchlistModel
 */
export type PlexWatchlistModel = {
    /**
     * Update Interval
     */
    update_interval?: number;
    /**
     * Enabled
     */
    enabled?: boolean;
    /**
     * Rss
     */
    rss?: Array<string>;
};

/**
 * PostProcessing
 */
export type PostProcessing = {
    subliminal?: SubliminalConfig;
};

/**
 * ProwlarrConfig
 */
export type ProwlarrConfig = {
    /**
     * Enabled
     */
    enabled?: boolean;
    /**
     * Url
     */
    url?: string;
    /**
     * Api Key
     */
    api_key?: string;
    /**
     * Timeout
     */
    timeout?: number;
    /**
     * Ratelimit
     */
    ratelimit?: boolean;
    /**
     * Limiter Seconds
     */
    limiter_seconds?: number;
};

/**
 * QualityRankModel
 * Ranking configuration for quality attributes.
 */
export type QualityRankModel = {
    av1?: CustomRank;
    avc?: CustomRank;
    bluray?: CustomRank;
    dvd?: CustomRank;
    hdtv?: CustomRank;
    hevc?: CustomRank;
    mpeg?: CustomRank;
    remux?: CustomRank;
    vhs?: CustomRank;
    web?: CustomRank;
    webdl?: CustomRank;
    webmux?: CustomRank;
    xvid?: CustomRank;
};

/**
 * RDUser
 */
export type RdUser = {
    /**
     * Id
     */
    id: number;
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Points
     * User's RD points
     */
    points: number;
    /**
     * Locale
     */
    locale: string;
    /**
     * Avatar
     * URL to the user's avatar
     */
    avatar: string;
    /**
     * Type
     */
    type: 'free' | 'premium';
    /**
     * Premium
     * Premium subscription left in seconds
     */
    premium: number;
};

/**
 * RTNSettingsModel
 */
export type RtnSettingsModel = {
    /**
     * Profile
     * Identifier for the settings profile
     */
    profile?: string;
    /**
     * Require
     * Patterns torrents must match to be considered
     */
    require?: Array<string>;
    /**
     * Exclude
     * Patterns that, if matched, result in torrent exclusion
     */
    exclude?: Array<string>;
    /**
     * Preferred
     * Patterns indicating preferred attributes in torrents
     */
    preferred?: Array<string>;
    /**
     * Configuration for enabled resolutions
     */
    resolutions?: ResolutionConfig;
    /**
     * General options for torrent filtering and ranking
     */
    options?: OptionsConfig;
    /**
     * Language preferences and restrictions
     */
    languages?: LanguagesConfig;
    /**
     * Custom ranking configurations for specific attributes
     */
    custom_ranks?: CustomRanksConfig;
};

/**
 * RarbgConfig
 */
export type RarbgConfig = {
    /**
     * Enabled
     */
    enabled?: boolean;
    /**
     * Url
     */
    url?: string;
    /**
     * Timeout
     */
    timeout?: number;
    /**
     * Ratelimit
     */
    ratelimit?: boolean;
};

/**
 * RealDebridModel
 */
export type RealDebridModel = {
    /**
     * Enabled
     */
    enabled?: boolean;
    /**
     * Api Key
     */
    api_key?: string;
};

/**
 * ReindexResponse
 */
export type ReindexResponse = {
    /**
     * Message
     */
    message: string;
};

/**
 * RemoveResponse
 */
export type RemoveResponse = {
    /**
     * Message
     */
    message: string;
    /**
     * Ids
     */
    ids: Array<number>;
};

/**
 * ResetResponse
 */
export type ResetResponse = {
    /**
     * Message
     */
    message: string;
    /**
     * Ids
     */
    ids: Array<number>;
};

/**
 * ResolutionConfig
 * Configuration for which resolutions are enabled.
 */
export type ResolutionConfig = {
    /**
     * R2160P
     */
    r2160p?: boolean;
    /**
     * R1080P
     */
    r1080p?: boolean;
    /**
     * R720P
     */
    r720p?: boolean;
    /**
     * R480P
     */
    r480p?: boolean;
    /**
     * R360P
     */
    r360p?: boolean;
    /**
     * Unknown
     */
    unknown?: boolean;
};

/**
 * RetryResponse
 */
export type RetryResponse = {
    /**
     * Message
     */
    message: string;
    /**
     * Ids
     */
    ids: Array<string>;
};

/**
 * RipsRankModel
 * Ranking configuration for rips attributes.
 */
export type RipsRankModel = {
    bdrip?: CustomRank;
    brrip?: CustomRank;
    dvdrip?: CustomRank;
    hdrip?: CustomRank;
    ppvrip?: CustomRank;
    satrip?: CustomRank;
    tvrip?: CustomRank;
    uhdrip?: CustomRank;
    vhsrip?: CustomRank;
    webdlrip?: CustomRank;
    webrip?: CustomRank;
};

/**
 * RootResponse
 */
export type RootResponse = {
    /**
     * Message
     */
    message: string;
    /**
     * Tmdb Ids
     */
    tmdb_ids?: Array<string>;
    /**
     * Tvdb Ids
     */
    tvdb_ids?: Array<string>;
    /**
     * Version
     */
    version: string;
};

/**
 * ScrapeItemResponse
 */
export type ScrapeItemResponse = {
    /**
     * Message
     */
    message: string;
    /**
     * Streams
     */
    streams: {
        [key: string]: Stream;
    };
};

/**
 * ScraperModel
 */
export type ScraperModel = {
    /**
     * After 2
     */
    after_2?: number;
    /**
     * After 5
     */
    after_5?: number;
    /**
     * After 10
     */
    after_10?: number;
    /**
     * Enable Aliases
     */
    enable_aliases?: boolean;
    /**
     * Bucket Limit
     */
    bucket_limit?: number;
    /**
     * Max Failed Attempts
     */
    max_failed_attempts?: number;
    /**
     * Dubbed Anime Only
     */
    dubbed_anime_only?: boolean;
    torrentio?: TorrentioConfig;
    jackett?: JackettConfig;
    prowlarr?: ProwlarrConfig;
    orionoid?: OrionoidConfig;
    mediafusion?: MediafusionConfig;
    zilean?: ZileanConfig;
    comet?: CometConfig;
    rarbg?: RarbgConfig;
};

/**
 * SelectFilesResponse
 */
export type SelectFilesResponse = {
    /**
     * Message
     */
    message: string;
    /**
     * Download Type
     */
    download_type: 'cached' | 'uncached';
};

/**
 * SessionResponse
 */
export type SessionResponse = {
    /**
     * Message
     */
    message: string;
};

/**
 * SetSettings
 */
export type SetSettings = {
    /**
     * Key
     */
    key: string;
    /**
     * Value
     */
    value: unknown;
};

/**
 * ShowFileData
 * Root model for show file data that maps seasons to episodes to file data.
 *
 * Example:
 * {
 * 1: {  # Season 1
 * 1: {"filename": "path/to/s01e01.mkv"},  # Episode 1
 * 2: {"filename": "path/to/s01e02.mkv"}   # Episode 2
 * },
 * 2: {  # Season 2
 * 1: {"filename": "path/to/s02e01.mkv"}   # Episode 1
 * }
 * }
 */
export type ShowFileData = {
    [key: string]: {
        [key: string]: DebridFile;
    };
};

/**
 * StartSessionResponse
 */
export type StartSessionResponse = {
    /**
     * Message
     */
    message: string;
    /**
     * Session Id
     */
    session_id: string;
    /**
     * Torrent Id
     */
    torrent_id: string;
    torrent_info: TorrentInfo;
    containers: TorrentContainer | null;
    /**
     * Expires At
     */
    expires_at: string;
};

/**
 * StateResponse
 */
export type StateResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * States
     */
    states: Array<string>;
};

/**
 * States
 */
export type States = 'Unknown' | 'Unreleased' | 'Ongoing' | 'Requested' | 'Indexed' | 'Scraped' | 'Downloaded' | 'Symlinked' | 'Completed' | 'PartiallyCompleted' | 'Failed' | 'Paused';

/**
 * StatsResponse
 */
export type StatsResponse = {
    /**
     * Total Items
     */
    total_items: number;
    /**
     * Total Movies
     */
    total_movies: number;
    /**
     * Total Shows
     */
    total_shows: number;
    /**
     * Total Seasons
     */
    total_seasons: number;
    /**
     * Total Episodes
     */
    total_episodes: number;
    /**
     * Total Symlinks
     */
    total_symlinks: number;
    /**
     * Incomplete Items
     */
    incomplete_items: number;
    /**
     * Incomplete Retries
     * Media item log string: number of retries
     */
    incomplete_retries: {
        [key: string]: number;
    };
    /**
     * States
     */
    states: {
        [key in States]?: number;
    };
};

/**
 * Stream
 */
export type Stream = {
    /**
     * Infohash
     */
    infohash: string;
    /**
     * Raw Title
     */
    raw_title: string;
    /**
     * Parsed Title
     */
    parsed_title: string;
    parsed_data: ParsedData;
    /**
     * Rank
     */
    rank: number;
    /**
     * Lev Ratio
     */
    lev_ratio: number;
    /**
     * Is Cached
     */
    is_cached?: boolean;
};

/**
 * SubliminalConfig
 */
export type SubliminalConfig = {
    /**
     * Enabled
     */
    enabled?: boolean;
    /**
     * Languages
     */
    languages?: Array<string>;
    /**
     * Providers
     */
    providers?: {
        [key: string]: unknown;
    };
};

/**
 * TorBoxModel
 */
export type TorBoxModel = {
    /**
     * Enabled
     */
    enabled?: boolean;
    /**
     * Api Key
     */
    api_key?: string;
};

/**
 * TorrentContainer
 * Represents a collection of files from an infohash from a debrid service
 */
export type TorrentContainer = {
    /**
     * Infohash
     */
    infohash: string;
    /**
     * Files
     */
    files?: Array<DebridFile>;
};

/**
 * TorrentInfo
 * Torrent information from a debrid service
 */
export type TorrentInfo = {
    /**
     * Id
     */
    id: number | string;
    /**
     * Name
     */
    name: string;
    /**
     * Status
     */
    status?: string | null;
    /**
     * Infohash
     */
    infohash?: string | null;
    /**
     * Progress
     */
    progress?: number | null;
    /**
     * Bytes
     */
    bytes?: number | null;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Expires At
     */
    expires_at?: string | null;
    /**
     * Completed At
     */
    completed_at?: string | null;
    /**
     * Alternative Filename
     */
    alternative_filename?: string | null;
    /**
     * Files
     */
    files?: {
        [key: string]: {
            [key: string]: number | string;
        };
    };
    /**
     * Links
     */
    links?: Array<string>;
};

/**
 * TorrentioConfig
 */
export type TorrentioConfig = {
    /**
     * Enabled
     */
    enabled?: boolean;
    /**
     * Filter
     */
    filter?: string;
    /**
     * Url
     */
    url?: string;
    /**
     * Timeout
     */
    timeout?: number;
    /**
     * Ratelimit
     */
    ratelimit?: boolean;
    /**
     * Proxy Url
     */
    proxy_url?: string;
};

/**
 * TraktModel
 */
export type TraktModel = {
    /**
     * Update Interval
     */
    update_interval?: number;
    /**
     * Enabled
     */
    enabled?: boolean;
    /**
     * Api Key
     */
    api_key?: string;
    /**
     * Watchlist
     */
    watchlist?: Array<string>;
    /**
     * User Lists
     */
    user_lists?: Array<string>;
    /**
     * Collection
     */
    collection?: Array<string>;
    /**
     * Fetch Trending
     */
    fetch_trending?: boolean;
    /**
     * Trending Count
     */
    trending_count?: number;
    /**
     * Fetch Popular
     */
    fetch_popular?: boolean;
    /**
     * Popular Count
     */
    popular_count?: number;
    /**
     * Fetch Most Watched
     */
    fetch_most_watched?: boolean;
    /**
     * Most Watched Period
     */
    most_watched_period?: string;
    /**
     * Most Watched Count
     */
    most_watched_count?: number;
    oauth?: TraktOauthModel;
    /**
     * Proxy Url
     */
    proxy_url?: string;
};

/**
 * TraktOAuthInitiateResponse
 */
export type TraktOAuthInitiateResponse = {
    /**
     * Auth Url
     */
    auth_url: string;
};

/**
 * TraktOauthModel
 */
export type TraktOauthModel = {
    /**
     * Oauth Client Id
     */
    oauth_client_id?: string;
    /**
     * Oauth Client Secret
     */
    oauth_client_secret?: string;
    /**
     * Oauth Redirect Uri
     */
    oauth_redirect_uri?: string;
    /**
     * Access Token
     */
    access_token?: string;
    /**
     * Refresh Token
     */
    refresh_token?: string;
};

/**
 * TrashRankModel
 * Ranking configuration for trash attributes.
 */
export type TrashRankModel = {
    cam?: CustomRank;
    clean_audio?: CustomRank;
    pdtv?: CustomRank;
    r5?: CustomRank;
    screener?: CustomRank;
    size?: CustomRank;
    telecine?: CustomRank;
    telesync?: CustomRank;
};

/**
 * UpdateAttributesResponse
 */
export type UpdateAttributesResponse = {
    /**
     * Message
     */
    message: string;
};

/**
 * UpdateNewReleasesResponse
 */
export type UpdateNewReleasesResponse = {
    /**
     * Message
     */
    message: string;
    /**
     * Updated Items
     */
    updated_items: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * UpdateOngoingResponse
 */
export type UpdateOngoingResponse = {
    /**
     * Message
     */
    message: string;
    /**
     * Updated Items
     */
    updated_items: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * UpdatersModel
 */
export type UpdatersModel = {
    /**
     * Updater Interval
     */
    updater_interval?: number;
    /**
     * Library Path
     */
    library_path?: string;
    plex?: PlexLibraryModel;
    jellyfin?: JellyfinLibraryModel;
    emby?: EmbyLibraryModel;
};

/**
 * UploadLogsResponse
 */
export type UploadLogsResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Url
     * URL to the uploaded log file. 50M Filesize limit. 180 day retention.
     */
    url: string;
};

/**
 * VFSStatsResponse
 */
export type VfsStatsResponse = {
    /**
     * Stats
     * VFS statistics
     */
    stats: {
        [key: string]: {
            [key: string]: unknown;
        };
    };
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * ZileanConfig
 */
export type ZileanConfig = {
    /**
     * Enabled
     */
    enabled?: boolean;
    /**
     * Url
     */
    url?: string;
    /**
     * Timeout
     */
    timeout?: number;
    /**
     * Ratelimit
     */
    ratelimit?: boolean;
};

/**
 * EventResponse
 */
export type RoutersSecureDefaultEventResponse = {
    /**
     * Events
     */
    events: {
        [key: string]: Array<number>;
    };
};

/**
 * EventResponse
 */
export type RoutersSecureStreamEventResponse = {
    /**
     * Data
     */
    data: {
        [key: string]: unknown;
    };
};

export type RootData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/';
};

export type RootResponses = {
    /**
     * Successful Response
     */
    200: RootResponse;
};

export type RootResponse2 = RootResponses[keyof RootResponses];

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type HealthErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type HealthResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type HealthResponse = HealthResponses[keyof HealthResponses];

export type RdData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/rd';
};

export type RdErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type RdResponses = {
    /**
     * Successful Response
     */
    200: RdUser;
};

export type RdResponse = RdResponses[keyof RdResponses];

export type GenerateapikeyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/generateapikey';
};

export type GenerateapikeyErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type GenerateapikeyResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type GenerateapikeyResponse = GenerateapikeyResponses[keyof GenerateapikeyResponses];

export type ServicesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/services';
};

export type ServicesErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type ServicesResponses = {
    /**
     * Response Services
     * Successful Response
     */
    200: {
        [key: string]: boolean;
    };
};

export type ServicesResponse = ServicesResponses[keyof ServicesResponses];

export type TraktOauthInitiateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/trakt/oauth/initiate';
};

export type TraktOauthInitiateErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type TraktOauthInitiateResponses = {
    /**
     * Successful Response
     */
    200: TraktOAuthInitiateResponse;
};

export type TraktOauthInitiateResponse = TraktOauthInitiateResponses[keyof TraktOauthInitiateResponses];

export type TraktOauthCallbackData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Code
         */
        code: string;
    };
    url: '/api/v1/trakt/oauth/callback';
};

export type TraktOauthCallbackErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TraktOauthCallbackError = TraktOauthCallbackErrors[keyof TraktOauthCallbackErrors];

export type TraktOauthCallbackResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type TraktOauthCallbackResponse = TraktOauthCallbackResponses[keyof TraktOauthCallbackResponses];

export type StatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/stats';
};

export type StatsErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type StatsResponses = {
    /**
     * Successful Response
     */
    200: StatsResponse;
};

export type StatsResponse2 = StatsResponses[keyof StatsResponses];

export type LogsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/logs';
};

export type LogsErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type LogsResponses = {
    /**
     * Successful Response
     */
    200: LogsResponse;
};

export type LogsResponse2 = LogsResponses[keyof LogsResponses];

export type EventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/events';
};

export type EventsErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type EventsResponses = {
    /**
     * Successful Response
     */
    200: RoutersSecureDefaultEventResponse;
};

export type EventsResponse = EventsResponses[keyof EventsResponses];

export type MountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/mount';
};

export type MountErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type MountResponses = {
    /**
     * Successful Response
     */
    200: MountResponse;
};

export type MountResponse2 = MountResponses[keyof MountResponses];

export type UploadLogsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/upload_logs';
};

export type UploadLogsErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type UploadLogsResponses = {
    /**
     * Successful Response
     */
    200: UploadLogsResponse;
};

export type UploadLogsResponse2 = UploadLogsResponses[keyof UploadLogsResponses];

export type FetchCalendarData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/calendar';
};

export type FetchCalendarErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type FetchCalendarResponses = {
    /**
     * Successful Response
     */
    200: CalendarResponse;
};

export type FetchCalendarResponse = FetchCalendarResponses[keyof FetchCalendarResponses];

export type GetVfsStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/vfs_stats';
};

export type GetVfsStatsErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type GetVfsStatsResponses = {
    /**
     * Successful Response
     */
    200: VfsStatsResponse;
};

export type GetVfsStatsResponse = GetVfsStatsResponses[keyof GetVfsStatsResponses];

export type GetStatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/items/states';
};

export type GetStatesErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type GetStatesResponses = {
    /**
     * Successful Response
     */
    200: StateResponse;
};

export type GetStatesResponse = GetStatesResponses[keyof GetStatesResponses];

export type GetItemsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number | null;
        /**
         * Page
         */
        page?: number | null;
        /**
         * Type
         */
        type?: string | null;
        /**
         * States
         */
        states?: string | null;
        /**
         * Sort
         */
        sort?: ('date_desc' | 'date_asc' | 'title_asc' | 'title_desc') | null;
        /**
         * Search
         */
        search?: string | null;
        /**
         * Extended
         */
        extended?: boolean | null;
        /**
         * Is Anime
         */
        is_anime?: boolean | null;
    };
    url: '/api/v1/items';
};

export type GetItemsErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetItemsError = GetItemsErrors[keyof GetItemsErrors];

export type GetItemsResponses = {
    /**
     * Successful Response
     */
    200: ItemsResponse;
};

export type GetItemsResponse = GetItemsResponses[keyof GetItemsResponses];

export type AddItemsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Tmdb Ids
         */
        tmdb_ids?: string | null;
        /**
         * Tvdb Ids
         */
        tvdb_ids?: string | null;
        /**
         * Media Type
         */
        media_type?: ('movie' | 'tv') | null;
    };
    url: '/api/v1/items/add';
};

export type AddItemsErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddItemsError = AddItemsErrors[keyof AddItemsErrors];

export type AddItemsResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type AddItemsResponse = AddItemsResponses[keyof AddItemsResponses];

export type GetItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: {
        /**
         * Media Type
         */
        media_type?: 'movie' | 'tv' | 'item';
        /**
         * With Streams
         */
        with_streams?: boolean | null;
    };
    url: '/api/v1/items/{id}';
};

export type GetItemErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetItemError = GetItemErrors[keyof GetItemErrors];

export type GetItemResponses = {
    /**
     * Response Get Item
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetItemResponse = GetItemResponses[keyof GetItemResponses];

export type ResetItemsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Ids
         */
        ids: string;
    };
    url: '/api/v1/items/reset';
};

export type ResetItemsErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetItemsError = ResetItemsErrors[keyof ResetItemsErrors];

export type ResetItemsResponses = {
    /**
     * Successful Response
     */
    200: ResetResponse;
};

export type ResetItemsResponse = ResetItemsResponses[keyof ResetItemsResponses];

export type RetryItemsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Ids
         */
        ids: string;
    };
    url: '/api/v1/items/retry';
};

export type RetryItemsErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RetryItemsError = RetryItemsErrors[keyof RetryItemsErrors];

export type RetryItemsResponses = {
    /**
     * Successful Response
     */
    200: RetryResponse;
};

export type RetryItemsResponse = RetryItemsResponses[keyof RetryItemsResponses];

export type RetryLibraryItemsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/items/retry_library';
};

export type RetryLibraryItemsErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type RetryLibraryItemsResponses = {
    /**
     * Successful Response
     */
    200: RetryResponse;
};

export type RetryLibraryItemsResponse = RetryLibraryItemsResponses[keyof RetryLibraryItemsResponses];

export type UpdateOngoingItemsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/items/update_ongoing';
};

export type UpdateOngoingItemsErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type UpdateOngoingItemsResponses = {
    /**
     * Successful Response
     */
    200: UpdateOngoingResponse;
};

export type UpdateOngoingItemsResponse = UpdateOngoingItemsResponses[keyof UpdateOngoingItemsResponses];

export type UpdateNewReleasesItemsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Update Type
         */
        update_type?: 'series' | 'seasons' | 'episodes';
        /**
         * Hours
         */
        hours?: number | null;
    };
    url: '/api/v1/items/update_new_releases';
};

export type UpdateNewReleasesItemsErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateNewReleasesItemsError = UpdateNewReleasesItemsErrors[keyof UpdateNewReleasesItemsErrors];

export type UpdateNewReleasesItemsResponses = {
    /**
     * Successful Response
     */
    200: UpdateNewReleasesResponse;
};

export type UpdateNewReleasesItemsResponse = UpdateNewReleasesItemsResponses[keyof UpdateNewReleasesItemsResponses];

export type RemoveItemData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Ids
         */
        ids: string;
    };
    url: '/api/v1/items/remove';
};

export type RemoveItemErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveItemError = RemoveItemErrors[keyof RemoveItemErrors];

export type RemoveItemResponses = {
    /**
     * Successful Response
     */
    200: RemoveResponse;
};

export type RemoveItemResponse = RemoveItemResponses[keyof RemoveItemResponses];

export type GetItemStreamsApiV1ItemsItemIdStreamsGetData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: number;
    };
    query?: never;
    url: '/api/v1/items/{item_id}/streams';
};

export type GetItemStreamsApiV1ItemsItemIdStreamsGetErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetItemStreamsApiV1ItemsItemIdStreamsGetError = GetItemStreamsApiV1ItemsItemIdStreamsGetErrors[keyof GetItemStreamsApiV1ItemsItemIdStreamsGetErrors];

export type GetItemStreamsApiV1ItemsItemIdStreamsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type BlacklistStreamApiV1ItemsItemIdStreamsStreamIdBlacklistPostData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: number;
        /**
         * Stream Id
         */
        stream_id: number;
    };
    query?: never;
    url: '/api/v1/items/{item_id}/streams/{stream_id}/blacklist';
};

export type BlacklistStreamApiV1ItemsItemIdStreamsStreamIdBlacklistPostErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BlacklistStreamApiV1ItemsItemIdStreamsStreamIdBlacklistPostError = BlacklistStreamApiV1ItemsItemIdStreamsStreamIdBlacklistPostErrors[keyof BlacklistStreamApiV1ItemsItemIdStreamsStreamIdBlacklistPostErrors];

export type BlacklistStreamApiV1ItemsItemIdStreamsStreamIdBlacklistPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UnblacklistStreamApiV1ItemsItemIdStreamsStreamIdUnblacklistPostData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: number;
        /**
         * Stream Id
         */
        stream_id: number;
    };
    query?: never;
    url: '/api/v1/items/{item_id}/streams/{stream_id}/unblacklist';
};

export type UnblacklistStreamApiV1ItemsItemIdStreamsStreamIdUnblacklistPostErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UnblacklistStreamApiV1ItemsItemIdStreamsStreamIdUnblacklistPostError = UnblacklistStreamApiV1ItemsItemIdStreamsStreamIdUnblacklistPostErrors[keyof UnblacklistStreamApiV1ItemsItemIdStreamsStreamIdUnblacklistPostErrors];

export type UnblacklistStreamApiV1ItemsItemIdStreamsStreamIdUnblacklistPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ResetItemStreamsData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: number;
    };
    query?: never;
    url: '/api/v1/items/{item_id}/streams/reset';
};

export type ResetItemStreamsErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetItemStreamsError = ResetItemStreamsErrors[keyof ResetItemStreamsErrors];

export type ResetItemStreamsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PauseItemsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Ids
         */
        ids: string;
    };
    url: '/api/v1/items/pause';
};

export type PauseItemsErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PauseItemsError = PauseItemsErrors[keyof PauseItemsErrors];

export type PauseItemsResponses = {
    /**
     * Successful Response
     */
    200: PauseResponse;
};

export type PauseItemsResponse = PauseItemsResponses[keyof PauseItemsResponses];

export type UnpauseItemsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Ids
         */
        ids: string;
    };
    url: '/api/v1/items/unpause';
};

export type UnpauseItemsErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UnpauseItemsError = UnpauseItemsErrors[keyof UnpauseItemsErrors];

export type UnpauseItemsResponses = {
    /**
     * Successful Response
     */
    200: PauseResponse;
};

export type UnpauseItemsResponse = UnpauseItemsResponses[keyof UnpauseItemsResponses];

export type CompositeReindexerData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Item Id
         */
        item_id?: number | null;
        /**
         * Tvdb Id
         */
        tvdb_id?: string | null;
        /**
         * Tmdb Id
         */
        tmdb_id?: string | null;
        /**
         * Imdb Id
         */
        imdb_id?: string | null;
    };
    url: '/api/v1/items/reindex';
};

export type CompositeReindexerErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CompositeReindexerError = CompositeReindexerErrors[keyof CompositeReindexerErrors];

export type CompositeReindexerResponses = {
    /**
     * Successful Response
     */
    200: ReindexResponse;
};

export type CompositeReindexerResponse = CompositeReindexerResponses[keyof CompositeReindexerResponses];

export type FfprobeMediaFilesData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Id
         */
        id: number;
    };
    url: '/api/v1/items/ffprobe';
};

export type FfprobeMediaFilesErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FfprobeMediaFilesError = FfprobeMediaFilesErrors[keyof FfprobeMediaFilesErrors];

export type FfprobeMediaFilesResponses = {
    /**
     * Successful Response
     */
    200: FfprobeResponse;
};

export type FfprobeMediaFilesResponse = FfprobeMediaFilesResponses[keyof FfprobeMediaFilesResponses];

export type ScrapeItemData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Item Id
         */
        item_id?: string | null;
        /**
         * Tmdb Id
         */
        tmdb_id?: string | null;
        /**
         * Tvdb Id
         */
        tvdb_id?: string | null;
        /**
         * Imdb Id
         */
        imdb_id?: string | null;
        /**
         * Media Type
         */
        media_type?: ('movie' | 'tv') | null;
    };
    url: '/api/v1/scrape/scrape';
};

export type ScrapeItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScrapeItemError = ScrapeItemErrors[keyof ScrapeItemErrors];

export type ScrapeItemResponses = {
    /**
     * Successful Response
     */
    200: ScrapeItemResponse;
};

export type ScrapeItemResponse2 = ScrapeItemResponses[keyof ScrapeItemResponses];

export type StartManualSessionData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Item Id
         */
        item_id?: string | null;
        /**
         * Tmdb Id
         */
        tmdb_id?: string | null;
        /**
         * Tvdb Id
         */
        tvdb_id?: string | null;
        /**
         * Imdb Id
         */
        imdb_id?: string | null;
        /**
         * Media Type
         */
        media_type?: ('movie' | 'tv') | null;
        /**
         * Magnet
         */
        magnet?: string | null;
    };
    url: '/api/v1/scrape/scrape/start_session';
};

export type StartManualSessionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartManualSessionError = StartManualSessionErrors[keyof StartManualSessionErrors];

export type StartManualSessionResponses = {
    /**
     * Successful Response
     */
    200: StartSessionResponse;
};

export type StartManualSessionResponse = StartManualSessionResponses[keyof StartManualSessionResponses];

export type ManualSelectData = {
    body: Container;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/scrape/scrape/select_files/{session_id}';
};

export type ManualSelectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ManualSelectError = ManualSelectErrors[keyof ManualSelectErrors];

export type ManualSelectResponses = {
    /**
     * Successful Response
     */
    200: SelectFilesResponse;
};

export type ManualSelectResponse = ManualSelectResponses[keyof ManualSelectResponses];

export type ManualUpdateAttributesData = {
    /**
     * Data
     */
    body: DebridFile | ShowFileData;
    path: {
        /**
         * Session Id
         */
        session_id: unknown;
    };
    query?: never;
    url: '/api/v1/scrape/scrape/update_attributes/{session_id}';
};

export type ManualUpdateAttributesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ManualUpdateAttributesError = ManualUpdateAttributesErrors[keyof ManualUpdateAttributesErrors];

export type ManualUpdateAttributesResponses = {
    /**
     * Successful Response
     */
    200: UpdateAttributesResponse;
};

export type ManualUpdateAttributesResponse = ManualUpdateAttributesResponses[keyof ManualUpdateAttributesResponses];

export type AbortManualSessionData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/scrape/scrape/abort_session/{session_id}';
};

export type AbortManualSessionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AbortManualSessionError = AbortManualSessionErrors[keyof AbortManualSessionErrors];

export type AbortManualSessionResponses = {
    /**
     * Successful Response
     */
    200: SessionResponse;
};

export type AbortManualSessionResponse = AbortManualSessionResponses[keyof AbortManualSessionResponses];

export type CompleteManualSessionData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/scrape/scrape/complete_session/{session_id}';
};

export type CompleteManualSessionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CompleteManualSessionError = CompleteManualSessionErrors[keyof CompleteManualSessionErrors];

export type CompleteManualSessionResponses = {
    /**
     * Successful Response
     */
    200: SessionResponse;
};

export type CompleteManualSessionResponse = CompleteManualSessionResponses[keyof CompleteManualSessionResponses];

export type ParseTorrentTitlesData = {
    /**
     * Titles
     */
    body: Array<string>;
    path?: never;
    query?: never;
    url: '/api/v1/scrape/parse';
};

export type ParseTorrentTitlesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ParseTorrentTitlesError = ParseTorrentTitlesErrors[keyof ParseTorrentTitlesErrors];

export type ParseTorrentTitlesResponses = {
    /**
     * Successful Response
     */
    200: ParseTorrentTitleResponse;
};

export type ParseTorrentTitlesResponse = ParseTorrentTitlesResponses[keyof ParseTorrentTitlesResponses];

export type GetSettingsSchemaData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/settings/schema';
};

export type GetSettingsSchemaErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type GetSettingsSchemaResponses = {
    /**
     * Response Get Settings Schema
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetSettingsSchemaResponse = GetSettingsSchemaResponses[keyof GetSettingsSchemaResponses];

export type LoadSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/settings/load';
};

export type LoadSettingsErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type LoadSettingsResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type LoadSettingsResponse = LoadSettingsResponses[keyof LoadSettingsResponses];

export type SaveSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/settings/save';
};

export type SaveSettingsErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type SaveSettingsResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type SaveSettingsResponse = SaveSettingsResponses[keyof SaveSettingsResponses];

export type GetAllSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/settings/get/all';
};

export type GetAllSettingsErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type GetAllSettingsResponses = {
    /**
     * Successful Response
     */
    200: AppModel;
};

export type GetAllSettingsResponse = GetAllSettingsResponses[keyof GetAllSettingsResponses];

export type GetSettingsData = {
    body?: never;
    path: {
        /**
         * Paths
         */
        paths: string;
    };
    query?: never;
    url: '/api/v1/settings/get/{paths}';
};

export type GetSettingsErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSettingsError = GetSettingsErrors[keyof GetSettingsErrors];

export type GetSettingsResponses = {
    /**
     * Response Get Settings
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetSettingsResponse = GetSettingsResponses[keyof GetSettingsResponses];

export type SetAllSettingsData = {
    /**
     * New Settings
     */
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/api/v1/settings/set/all';
};

export type SetAllSettingsErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetAllSettingsError = SetAllSettingsErrors[keyof SetAllSettingsErrors];

export type SetAllSettingsResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type SetAllSettingsResponse = SetAllSettingsResponses[keyof SetAllSettingsResponses];

export type SetSettingsData = {
    /**
     * Settings
     */
    body: Array<SetSettings>;
    path?: never;
    query?: never;
    url: '/api/v1/settings/set';
};

export type SetSettingsErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetSettingsError = SetSettingsErrors[keyof SetSettingsErrors];

export type SetSettingsResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type SetSettingsResponse = SetSettingsResponses[keyof SetSettingsResponses];

export type OverseerrApiV1WebhookOverseerrPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/webhook/overseerr';
};

export type OverseerrApiV1WebhookOverseerrPostErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type OverseerrApiV1WebhookOverseerrPostResponses = {
    /**
     * Response Overseerr Api V1 Webhook Overseerr Post
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type OverseerrApiV1WebhookOverseerrPostResponse = OverseerrApiV1WebhookOverseerrPostResponses[keyof OverseerrApiV1WebhookOverseerrPostResponses];

export type GetEventTypesApiV1StreamEventTypesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/stream/event_types';
};

export type GetEventTypesApiV1StreamEventTypesGetErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type GetEventTypesApiV1StreamEventTypesGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type StreamEventsApiV1StreamEventTypeGetData = {
    body?: never;
    path: {
        /**
         * Event Type
         */
        event_type: string;
    };
    query?: never;
    url: '/api/v1/stream/{event_type}';
};

export type StreamEventsApiV1StreamEventTypeGetErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StreamEventsApiV1StreamEventTypeGetError = StreamEventsApiV1StreamEventTypeGetErrors[keyof StreamEventsApiV1StreamEventTypeGetErrors];

export type StreamEventsApiV1StreamEventTypeGetResponses = {
    /**
     * Successful Response
     */
    200: RoutersSecureStreamEventResponse;
};

export type StreamEventsApiV1StreamEventTypeGetResponse = StreamEventsApiV1StreamEventTypeGetResponses[keyof StreamEventsApiV1StreamEventTypeGetResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};