volumes:
    riven-frontend-data:

services:
    riven-frontend:
        image: spoked/riven-frontend:v1-beta # Tags: latest/dev/x.x.x
        build:
            context: .
            dockerfile: Dockerfile
        container_name: riven-frontend
        restart: unless-stopped
        env_file:
            - .env # Load environment variables from .env file. Read .env.example

        # or set individual environment variables here, both methods can be used together, the ones set here will override those in the .env file if present
        environment:
            - TZ=Asia/Kolkata

        # Uncomment the following if you plan to bind the port to the host machine
        expose:
            - 3000

        # (Optional) Uncomment the following lines to bind the port to the host machine
        # ports:
        #   - 3000:3000
        volumes:
            - riven-frontend-data:/riven/data # Persistent data storage
