services:
  riven:
    image: spoked/riven-frontend:latest
    container_name: riven-frontend
    restart: unless-stopped
    tty: true
    environment:
      - BACKEND_URL=http://127.0.0.1:8080
      - TZ=America/New_York
    ports:
      - '3000:3000'
