volumes:
    riven-frontend-data:

services:
    riven-frontend:
        image: spoked/riven-frontend:latest # Tags: latest/dev/x.x.x
        build:
            context: .
            dockerfile: Dockerfile
        container_name: riven-frontend
        restart: unless-stopped
        env_file:
            - .env # Load environment variables from .env file
        environment:
            - ORIGIN=http://localhost:3000 # (Optional) No trailing slash, read more below
            - TZ=Asia/Kolkata
            - DATABASE_URL=/riven/data/riven.db

        # Uncomment the following if you plan to bind the port to the host machine
        expose:
            - 3000

        # (Optional) Uncomment the following lines to bind the port to the host machine
        # ports:
        #   - 3000:3000
        volumes:
            - riven-frontend-data:/riven/data # Persistent data storage
