// This file is auto-generated by @hey-api/openapi-ts

export const AllDebridModelSchema = {
    properties: {
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            default: false
        },
        api_key: {
            type: 'string',
            title: 'Api Key',
            default: ''
        }
    },
    type: 'object',
    title: 'AllDebridModel'
} as const;

export const AppModelSchema = {
    properties: {
        version: {
            type: 'string',
            title: 'Version',
            default: '0.21.18'
        },
        api_key: {
            type: 'string',
            title: 'Api Key',
            default: ''
        },
        debug: {
            type: 'boolean',
            title: 'Debug',
            default: true
        },
        debug_database: {
            type: 'boolean',
            title: 'Debug Database',
            default: false
        },
        log: {
            type: 'boolean',
            title: 'Log',
            default: true
        },
        force_refresh: {
            type: 'boolean',
            title: 'Force Refresh',
            default: false
        },
        map_metadata: {
            type: 'boolean',
            title: 'Map Metadata',
            default: true
        },
        tracemalloc: {
            type: 'boolean',
            title: 'Tracemalloc',
            default: false
        },
        symlink: {
            '$ref': '#/components/schemas/SymlinkModel',
            default: {
                rclone_path: '.',
                library_path: '.',
                separate_anime_dirs: false,
                repair_symlinks: false,
                repair_interval: 6
            }
        },
        updaters: {
            '$ref': '#/components/schemas/UpdatersModel',
            default: {
                updater_interval: 120,
                plex: {
                    enabled: false,
                    token: '',
                    url: 'http://localhost:32400'
                },
                jellyfin: {
                    api_key: '',
                    enabled: false,
                    url: 'http://localhost:8096'
                },
                emby: {
                    api_key: '',
                    enabled: false,
                    url: 'http://localhost:8096'
                }
            }
        },
        downloaders: {
            '$ref': '#/components/schemas/DownloadersModel',
            default: {
                video_extensions: ['mp4', 'mkv', 'avi'],
                movie_filesize_mb_min: 700,
                movie_filesize_mb_max: -1,
                episode_filesize_mb_min: 100,
                episode_filesize_mb_max: -1,
                proxy_url: '',
                real_debrid: {
                    api_key: '',
                    enabled: false
                },
                all_debrid: {
                    api_key: '',
                    enabled: false
                }
            }
        },
        content: {
            '$ref': '#/components/schemas/ContentModel',
            default: {
                overseerr: {
                    api_key: '',
                    enabled: false,
                    update_interval: 60,
                    url: 'http://localhost:5055',
                    use_webhook: false
                },
                plex_watchlist: {
                    enabled: false,
                    rss: [],
                    update_interval: 60
                },
                mdblist: {
                    api_key: '',
                    enabled: false,
                    lists: [],
                    update_interval: 86400
                },
                listrr: {
                    api_key: '',
                    enabled: false,
                    movie_lists: [],
                    show_lists: [],
                    update_interval: 86400
                },
                trakt: {
                    api_key: '',
                    collection: [],
                    enabled: false,
                    fetch_most_watched: false,
                    fetch_popular: false,
                    fetch_trending: false,
                    most_watched_count: 10,
                    most_watched_period: 'weekly',
                    oauth: {
                        access_token: '',
                        oauth_client_id: '',
                        oauth_client_secret: '',
                        oauth_redirect_uri: '',
                        refresh_token: ''
                    },
                    popular_count: 10,
                    trending_count: 10,
                    update_interval: 86400,
                    user_lists: [],
                    watchlist: []
                }
            }
        },
        scraping: {
            '$ref': '#/components/schemas/ScraperModel',
            default: {
                after_2: 2,
                after_5: 6,
                after_10: 24,
                parse_debug: false,
                enable_aliases: true,
                bucket_limit: 5,
                max_failed_attempts: 0,
                dubbed_anime_only: false,
                torrentio: {
                    enabled: false,
                    filter: 'sort=qualitysize%7Cqualityfilter=480p,scr,cam',
                    proxy_url: '',
                    ratelimit: true,
                    timeout: 30,
                    url: 'http://torrentio.strem.fun'
                },
                knightcrawler: {
                    enabled: false,
                    filter: 'sort=qualitysize%7Cqualityfilter=480p,scr,cam',
                    ratelimit: true,
                    timeout: 30,
                    url: 'https://knightcrawler.elfhosted.com'
                },
                jackett: {
                    api_key: '',
                    enabled: false,
                    ratelimit: true,
                    timeout: 30,
                    url: 'http://localhost:9117'
                },
                prowlarr: {
                    api_key: '',
                    enabled: false,
                    limiter_seconds: 60,
                    ratelimit: true,
                    timeout: 30,
                    url: 'http://localhost:9696'
                },
                orionoid: {
                    api_key: '',
                    cached_results_only: false,
                    enabled: false,
                    parameters: {
                        limitcount: 5,
                        video3d: 'false',
                        videoquality: 'sd_hd8k'
                    },
                    ratelimit: true,
                    timeout: 30
                },
                mediafusion: {
                    enabled: false,
                    ratelimit: true,
                    timeout: 30,
                    url: 'https://mediafusion.elfhosted.com'
                },
                zilean: {
                    enabled: false,
                    ratelimit: true,
                    timeout: 30,
                    url: 'http://localhost:8181'
                },
                comet: {
                    enabled: false,
                    ratelimit: true,
                    timeout: 30,
                    url: 'https://comet.elfhosted.com'
                }
            }
        },
        ranking: {
            '$ref': '#/components/schemas/RTNSettingsModel',
            default: {
                profile: 'default',
                require: [],
                exclude: [],
                preferred: [],
                resolutions: {
                    r1080p: true,
                    r2160p: false,
                    r360p: false,
                    r480p: false,
                    r720p: true,
                    unknown: true
                },
                options: {
                    allow_english_in_languages: true,
                    enable_fetch_speed_mode: true,
                    remove_adult_content: true,
                    remove_all_trash: true,
                    remove_ranks_under: -10000,
                    remove_unknown_languages: false,
                    title_similarity: 0.85
                },
                languages: {
                    exclude: [],
                    preferred: [],
                    required: []
                },
                custom_ranks: {
                    audio: {
                        aac: {
                            fetch: true,
                            rank: 0,
                            use_custom_rank: false
                        },
                        ac3: {
                            fetch: true,
                            rank: 0,
                            use_custom_rank: false
                        },
                        atmos: {
                            fetch: true,
                            rank: 0,
                            use_custom_rank: false
                        },
                        dolby_digital: {
                            fetch: true,
                            rank: 0,
                            use_custom_rank: false
                        },
                        dolby_digital_plus: {
                            fetch: true,
                            rank: 0,
                            use_custom_rank: false
                        },
                        dts_lossless: {
                            fetch: true,
                            rank: 0,
                            use_custom_rank: false
                        },
                        dts_lossy: {
                            fetch: true,
                            rank: 0,
                            use_custom_rank: false
                        },
                        eac3: {
                            fetch: true,
                            rank: 0,
                            use_custom_rank: false
                        },
                        flac: {
                            fetch: true,
                            rank: 0,
                            use_custom_rank: false
                        },
                        mono: {
                            fetch: false,
                            rank: 0,
                            use_custom_rank: false
                        },
                        mp3: {
                            fetch: false,
                            rank: 0,
                            use_custom_rank: false
                        },
                        stereo: {
                            fetch: true,
                            rank: 0,
                            use_custom_rank: false
                        },
                        surround: {
                            fetch: true,
                            rank: 0,
                            use_custom_rank: false
                        },
                        truehd: {
                            fetch: true,
                            rank: 0,
                            use_custom_rank: false
                        }
                    },
                    extras: {
                        '3d': {
                            fetch: false,
                            rank: 0,
                            use_custom_rank: false
                        },
                        converted: {
                            fetch: false,
                            rank: 0,
                            use_custom_rank: false
                        },
                        documentary: {
                            fetch: false,
                            rank: 0,
                            use_custom_rank: false
                        },
                        dubbed: {
                            fetch: true,
                            rank: 0,
                            use_custom_rank: false
                        },
                        edition: {
                            fetch: true,
                            rank: 0,
                            use_custom_rank: false
                        },
                        hardcoded: {
                            fetch: true,
                            rank: 0,
                            use_custom_rank: false
                        },
                        network: {
                            fetch: true,
                            rank: 0,
                            use_custom_rank: false
                        },
                        proper: {
                            fetch: true,
                            rank: 0,
                            use_custom_rank: false
                        },
                        repack: {
                            fetch: true,
                            rank: 0,
                            use_custom_rank: false
                        },
                        retail: {
                            fetch: true,
                            rank: 0,
                            use_custom_rank: false
                        },
                        scene: {
                            fetch: true,
                            rank: 0,
                            use_custom_rank: false
                        },
                        site: {
                            fetch: false,
                            rank: 0,
                            use_custom_rank: false
                        },
                        subbed: {
                            fetch: true,
                            rank: 0,
                            use_custom_rank: false
                        },
                        upscaled: {
                            fetch: false,
                            rank: 0,
                            use_custom_rank: false
                        }
                    },
                    hdr: {
                        bit10: {
                            fetch: true,
                            rank: 0,
                            use_custom_rank: false
                        },
                        dolby_vision: {
                            fetch: false,
                            rank: 0,
                            use_custom_rank: false
                        },
                        hdr: {
                            fetch: true,
                            rank: 0,
                            use_custom_rank: false
                        },
                        hdr10plus: {
                            fetch: true,
                            rank: 0,
                            use_custom_rank: false
                        },
                        sdr: {
                            fetch: true,
                            rank: 0,
                            use_custom_rank: false
                        }
                    },
                    quality: {
                        av1: {
                            fetch: false,
                            rank: 0,
                            use_custom_rank: false
                        },
                        avc: {
                            fetch: true,
                            rank: 0,
                            use_custom_rank: false
                        },
                        bluray: {
                            fetch: true,
                            rank: 0,
                            use_custom_rank: false
                        },
                        dvd: {
                            fetch: false,
                            rank: 0,
                            use_custom_rank: false
                        },
                        hdtv: {
                            fetch: true,
                            rank: 0,
                            use_custom_rank: false
                        },
                        hevc: {
                            fetch: true,
                            rank: 0,
                            use_custom_rank: false
                        },
                        mpeg: {
                            fetch: false,
                            rank: 0,
                            use_custom_rank: false
                        },
                        remux: {
                            fetch: false,
                            rank: 0,
                            use_custom_rank: false
                        },
                        vhs: {
                            fetch: false,
                            rank: 0,
                            use_custom_rank: false
                        },
                        web: {
                            fetch: true,
                            rank: 0,
                            use_custom_rank: false
                        },
                        webdl: {
                            fetch: true,
                            rank: 0,
                            use_custom_rank: false
                        },
                        webmux: {
                            fetch: false,
                            rank: 0,
                            use_custom_rank: false
                        },
                        xvid: {
                            fetch: false,
                            rank: 0,
                            use_custom_rank: false
                        }
                    },
                    rips: {
                        bdrip: {
                            fetch: false,
                            rank: 0,
                            use_custom_rank: false
                        },
                        brrip: {
                            fetch: true,
                            rank: 0,
                            use_custom_rank: false
                        },
                        dvdrip: {
                            fetch: false,
                            rank: 0,
                            use_custom_rank: false
                        },
                        hdrip: {
                            fetch: true,
                            rank: 0,
                            use_custom_rank: false
                        },
                        ppvrip: {
                            fetch: false,
                            rank: 0,
                            use_custom_rank: false
                        },
                        satrip: {
                            fetch: false,
                            rank: 0,
                            use_custom_rank: false
                        },
                        tvrip: {
                            fetch: false,
                            rank: 0,
                            use_custom_rank: false
                        },
                        uhdrip: {
                            fetch: false,
                            rank: 0,
                            use_custom_rank: false
                        },
                        vhsrip: {
                            fetch: false,
                            rank: 0,
                            use_custom_rank: false
                        },
                        webdlrip: {
                            fetch: false,
                            rank: 0,
                            use_custom_rank: false
                        },
                        webrip: {
                            fetch: true,
                            rank: 0,
                            use_custom_rank: false
                        }
                    },
                    trash: {
                        cam: {
                            fetch: false,
                            rank: 0,
                            use_custom_rank: false
                        },
                        clean_audio: {
                            fetch: false,
                            rank: 0,
                            use_custom_rank: false
                        },
                        pdtv: {
                            fetch: false,
                            rank: 0,
                            use_custom_rank: false
                        },
                        r5: {
                            fetch: false,
                            rank: 0,
                            use_custom_rank: false
                        },
                        screener: {
                            fetch: false,
                            rank: 0,
                            use_custom_rank: false
                        },
                        size: {
                            fetch: false,
                            rank: 0,
                            use_custom_rank: false
                        },
                        telecine: {
                            fetch: false,
                            rank: 0,
                            use_custom_rank: false
                        },
                        telesync: {
                            fetch: false,
                            rank: 0,
                            use_custom_rank: false
                        }
                    }
                }
            }
        },
        indexer: {
            '$ref': '#/components/schemas/IndexerModel',
            default: {
                update_interval: 3600
            }
        },
        database: {
            '$ref': '#/components/schemas/DatabaseModel',
            default: {
                host: 'postgresql+psycopg2://postgres:postgres@localhost/riven'
            }
        },
        notifications: {
            '$ref': '#/components/schemas/NotificationsModel',
            default: {
                enabled: false,
                title: 'Riven completed something!',
                on_item_type: ['movie', 'show', 'season'],
                service_urls: []
            }
        },
        post_processing: {
            '$ref': '#/components/schemas/PostProcessing',
            default: {
                subliminal: {
                    enabled: false,
                    languages: ['eng'],
                    providers: {
                        opensubtitles: {
                            enabled: false,
                            password: '',
                            username: ''
                        },
                        opensubtitlescom: {
                            enabled: false,
                            password: '',
                            username: ''
                        }
                    }
                }
            }
        }
    },
    type: 'object',
    title: 'AppModel'
} as const;

export const AudioRankModelSchema = {
    properties: {
        aac: {
            '$ref': '#/components/schemas/CustomRank'
        },
        ac3: {
            '$ref': '#/components/schemas/CustomRank'
        },
        atmos: {
            '$ref': '#/components/schemas/CustomRank'
        },
        dolby_digital: {
            '$ref': '#/components/schemas/CustomRank'
        },
        dolby_digital_plus: {
            '$ref': '#/components/schemas/CustomRank'
        },
        dts_lossy: {
            '$ref': '#/components/schemas/CustomRank'
        },
        dts_lossless: {
            '$ref': '#/components/schemas/CustomRank'
        },
        eac3: {
            '$ref': '#/components/schemas/CustomRank'
        },
        flac: {
            '$ref': '#/components/schemas/CustomRank'
        },
        mono: {
            '$ref': '#/components/schemas/CustomRank'
        },
        mp3: {
            '$ref': '#/components/schemas/CustomRank'
        },
        stereo: {
            '$ref': '#/components/schemas/CustomRank'
        },
        surround: {
            '$ref': '#/components/schemas/CustomRank'
        },
        truehd: {
            '$ref': '#/components/schemas/CustomRank'
        }
    },
    type: 'object',
    title: 'AudioRankModel',
    description: 'Ranking configuration for audio attributes.'
} as const;

export const CalendarResponseSchema = {
    properties: {
        data: {
            additionalProperties: true,
            type: 'object',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'CalendarResponse'
} as const;

export const CometConfigSchema = {
    properties: {
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            default: false
        },
        url: {
            type: 'string',
            title: 'Url',
            default: 'https://comet.elfhosted.com'
        },
        timeout: {
            type: 'integer',
            title: 'Timeout',
            default: 30
        },
        ratelimit: {
            type: 'boolean',
            title: 'Ratelimit',
            default: true
        }
    },
    type: 'object',
    title: 'CometConfig'
} as const;

export const ContainerSchema = {
    additionalProperties: {
        '$ref': '#/components/schemas/DebridFile'
    },
    type: 'object',
    title: 'Container',
    description: `Root model for container mapping file IDs to file information.

Example:
{
    "4": {
        "filename": "show.s01e01.mkv",
        "filesize": 30791392598
    },
    "5": {
        "filename": "show.s01e02.mkv",
        "filesize": 25573181861
    }
}`
} as const;

export const ContentModelSchema = {
    properties: {
        overseerr: {
            '$ref': '#/components/schemas/OverseerrModel',
            default: {
                update_interval: 60,
                enabled: false,
                url: 'http://localhost:5055',
                api_key: '',
                use_webhook: false
            }
        },
        plex_watchlist: {
            '$ref': '#/components/schemas/PlexWatchlistModel',
            default: {
                update_interval: 60,
                enabled: false,
                rss: []
            }
        },
        mdblist: {
            '$ref': '#/components/schemas/MdblistModel',
            default: {
                update_interval: 86400,
                enabled: false,
                api_key: '',
                lists: []
            }
        },
        listrr: {
            '$ref': '#/components/schemas/ListrrModel',
            default: {
                update_interval: 86400,
                enabled: false,
                movie_lists: [],
                show_lists: [],
                api_key: ''
            }
        },
        trakt: {
            '$ref': '#/components/schemas/TraktModel',
            default: {
                update_interval: 86400,
                enabled: false,
                api_key: '',
                watchlist: [],
                user_lists: [],
                collection: [],
                fetch_trending: false,
                trending_count: 10,
                fetch_popular: false,
                popular_count: 10,
                fetch_most_watched: false,
                most_watched_period: 'weekly',
                most_watched_count: 10,
                oauth: {
                    access_token: '',
                    oauth_client_id: '',
                    oauth_client_secret: '',
                    oauth_redirect_uri: '',
                    refresh_token: ''
                }
            }
        }
    },
    type: 'object',
    title: 'ContentModel'
} as const;

export const CustomRankSchema = {
    properties: {
        fetch: {
            type: 'boolean',
            title: 'Fetch',
            default: true
        },
        use_custom_rank: {
            type: 'boolean',
            title: 'Use Custom Rank',
            default: false
        },
        rank: {
            type: 'integer',
            title: 'Rank',
            default: 0
        }
    },
    type: 'object',
    title: 'CustomRank',
    description: 'Custom Ranks used in SettingsModel.'
} as const;

export const CustomRanksConfigSchema = {
    properties: {
        quality: {
            '$ref': '#/components/schemas/QualityRankModel'
        },
        rips: {
            '$ref': '#/components/schemas/RipsRankModel'
        },
        hdr: {
            '$ref': '#/components/schemas/HdrRankModel'
        },
        audio: {
            '$ref': '#/components/schemas/AudioRankModel'
        },
        extras: {
            '$ref': '#/components/schemas/ExtrasRankModel'
        },
        trash: {
            '$ref': '#/components/schemas/TrashRankModel'
        }
    },
    type: 'object',
    title: 'CustomRanksConfig',
    description: 'Configuration for custom ranks.'
} as const;

export const DatabaseModelSchema = {
    properties: {
        host: {
            type: 'string',
            title: 'Host',
            default: 'postgresql+psycopg2://postgres:postgres@localhost/riven'
        }
    },
    type: 'object',
    title: 'DatabaseModel'
} as const;

export const DebridFileSchema = {
    properties: {
        file_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'File Id'
        },
        filename: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Filename'
        },
        filesize: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Filesize'
        }
    },
    type: 'object',
    title: 'DebridFile',
    description: 'Represents a file from a debrid service'
} as const;

export const DownloadersModelSchema = {
    properties: {
        video_extensions: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Video Extensions',
            default: ['mp4', 'mkv', 'avi']
        },
        movie_filesize_mb_min: {
            type: 'integer',
            title: 'Movie Filesize Mb Min',
            default: 700
        },
        movie_filesize_mb_max: {
            type: 'integer',
            title: 'Movie Filesize Mb Max',
            default: -1
        },
        episode_filesize_mb_min: {
            type: 'integer',
            title: 'Episode Filesize Mb Min',
            default: 100
        },
        episode_filesize_mb_max: {
            type: 'integer',
            title: 'Episode Filesize Mb Max',
            default: -1
        },
        proxy_url: {
            type: 'string',
            title: 'Proxy Url',
            default: ''
        },
        real_debrid: {
            '$ref': '#/components/schemas/RealDebridModel',
            default: {
                enabled: false,
                api_key: ''
            }
        },
        all_debrid: {
            '$ref': '#/components/schemas/AllDebridModel',
            default: {
                enabled: false,
                api_key: ''
            }
        }
    },
    type: 'object',
    title: 'DownloadersModel'
} as const;

export const EmbyLibraryModelSchema = {
    properties: {
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            default: false
        },
        api_key: {
            type: 'string',
            title: 'Api Key',
            default: ''
        },
        url: {
            type: 'string',
            title: 'Url',
            default: 'http://localhost:8096'
        }
    },
    type: 'object',
    title: 'EmbyLibraryModel'
} as const;

export const ExtrasRankModelSchema = {
    properties: {
        '3d': {
            '$ref': '#/components/schemas/CustomRank'
        },
        converted: {
            '$ref': '#/components/schemas/CustomRank'
        },
        documentary: {
            '$ref': '#/components/schemas/CustomRank'
        },
        dubbed: {
            '$ref': '#/components/schemas/CustomRank'
        },
        edition: {
            '$ref': '#/components/schemas/CustomRank'
        },
        hardcoded: {
            '$ref': '#/components/schemas/CustomRank'
        },
        network: {
            '$ref': '#/components/schemas/CustomRank'
        },
        proper: {
            '$ref': '#/components/schemas/CustomRank'
        },
        repack: {
            '$ref': '#/components/schemas/CustomRank'
        },
        retail: {
            '$ref': '#/components/schemas/CustomRank'
        },
        site: {
            '$ref': '#/components/schemas/CustomRank'
        },
        subbed: {
            '$ref': '#/components/schemas/CustomRank'
        },
        upscaled: {
            '$ref': '#/components/schemas/CustomRank'
        },
        scene: {
            '$ref': '#/components/schemas/CustomRank'
        }
    },
    type: 'object',
    title: 'ExtrasRankModel',
    description: 'Ranking configuration for extras attributes.'
} as const;

export const FfprobeResponseSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        },
        data: {
            additionalProperties: true,
            type: 'object',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['message', 'data'],
    title: 'FfprobeResponse'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HdrRankModelSchema = {
    properties: {
        bit10: {
            '$ref': '#/components/schemas/CustomRank'
        },
        dolby_vision: {
            '$ref': '#/components/schemas/CustomRank'
        },
        hdr: {
            '$ref': '#/components/schemas/CustomRank'
        },
        hdr10plus: {
            '$ref': '#/components/schemas/CustomRank'
        },
        sdr: {
            '$ref': '#/components/schemas/CustomRank'
        }
    },
    type: 'object',
    title: 'HdrRankModel',
    description: 'Ranking configuration for HDR attributes.'
} as const;

export const IndexerModelSchema = {
    properties: {
        update_interval: {
            type: 'integer',
            title: 'Update Interval',
            default: 3600
        }
    },
    type: 'object',
    title: 'IndexerModel'
} as const;

export const ItemsResponseSchema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        items: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Items'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        limit: {
            type: 'integer',
            title: 'Limit'
        },
        total_items: {
            type: 'integer',
            title: 'Total Items'
        },
        total_pages: {
            type: 'integer',
            title: 'Total Pages'
        }
    },
    type: 'object',
    required: ['success', 'items', 'page', 'limit', 'total_items', 'total_pages'],
    title: 'ItemsResponse'
} as const;

export const JackettConfigSchema = {
    properties: {
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            default: false
        },
        url: {
            type: 'string',
            title: 'Url',
            default: 'http://localhost:9117'
        },
        api_key: {
            type: 'string',
            title: 'Api Key',
            default: ''
        },
        timeout: {
            type: 'integer',
            title: 'Timeout',
            default: 30
        },
        ratelimit: {
            type: 'boolean',
            title: 'Ratelimit',
            default: true
        }
    },
    type: 'object',
    title: 'JackettConfig'
} as const;

export const JellyfinLibraryModelSchema = {
    properties: {
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            default: false
        },
        api_key: {
            type: 'string',
            title: 'Api Key',
            default: ''
        },
        url: {
            type: 'string',
            title: 'Url',
            default: 'http://localhost:8096'
        }
    },
    type: 'object',
    title: 'JellyfinLibraryModel'
} as const;

export const KnightcrawlerConfigSchema = {
    properties: {
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            default: false
        },
        filter: {
            type: 'string',
            title: 'Filter',
            default: 'sort=qualitysize%7Cqualityfilter=480p,scr,cam'
        },
        url: {
            type: 'string',
            title: 'Url',
            default: 'https://knightcrawler.elfhosted.com'
        },
        timeout: {
            type: 'integer',
            title: 'Timeout',
            default: 30
        },
        ratelimit: {
            type: 'boolean',
            title: 'Ratelimit',
            default: true
        }
    },
    type: 'object',
    title: 'KnightcrawlerConfig'
} as const;

export const LanguagesConfigSchema = {
    properties: {
        required: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Required',
            default: []
        },
        exclude: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Exclude',
            default: []
        },
        preferred: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Preferred',
            default: []
        }
    },
    type: 'object',
    title: 'LanguagesConfig',
    description: 'Configuration for which languages are enabled.'
} as const;

export const ListrrModelSchema = {
    properties: {
        update_interval: {
            type: 'integer',
            title: 'Update Interval',
            default: 86400
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            default: false
        },
        movie_lists: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Movie Lists',
            default: []
        },
        show_lists: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Show Lists',
            default: []
        },
        api_key: {
            type: 'string',
            title: 'Api Key',
            default: ''
        }
    },
    type: 'object',
    title: 'ListrrModel'
} as const;

export const LogsResponseSchema = {
    properties: {
        logs: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Logs'
        }
    },
    type: 'object',
    required: ['logs'],
    title: 'LogsResponse'
} as const;

export const MdblistModelSchema = {
    properties: {
        update_interval: {
            type: 'integer',
            title: 'Update Interval',
            default: 86400
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            default: false
        },
        api_key: {
            type: 'string',
            title: 'Api Key',
            default: ''
        },
        lists: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Lists',
            default: []
        }
    },
    type: 'object',
    title: 'MdblistModel'
} as const;

export const MediafusionConfigSchema = {
    properties: {
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            default: false
        },
        url: {
            type: 'string',
            title: 'Url',
            default: 'https://mediafusion.elfhosted.com'
        },
        timeout: {
            type: 'integer',
            title: 'Timeout',
            default: 30
        },
        ratelimit: {
            type: 'boolean',
            title: 'Ratelimit',
            default: true
        }
    },
    type: 'object',
    title: 'MediafusionConfig'
} as const;

export const MessageResponseSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'MessageResponse'
} as const;

export const MountResponseSchema = {
    properties: {
        files: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Files'
        }
    },
    type: 'object',
    required: ['files'],
    title: 'MountResponse'
} as const;

export const NotificationsModelSchema = {
    properties: {
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            default: false
        },
        title: {
            type: 'string',
            title: 'Title',
            default: 'Riven completed something!'
        },
        on_item_type: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'On Item Type',
            default: ['movie', 'show', 'season']
        },
        service_urls: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Service Urls',
            default: []
        }
    },
    type: 'object',
    title: 'NotificationsModel'
} as const;

export const OptionsConfigSchema = {
    properties: {
        title_similarity: {
            type: 'number',
            title: 'Title Similarity',
            default: 0.85
        },
        remove_all_trash: {
            type: 'boolean',
            title: 'Remove All Trash',
            default: true
        },
        remove_ranks_under: {
            type: 'integer',
            title: 'Remove Ranks Under',
            default: -10000
        },
        remove_unknown_languages: {
            type: 'boolean',
            title: 'Remove Unknown Languages',
            default: false
        },
        allow_english_in_languages: {
            type: 'boolean',
            title: 'Allow English In Languages',
            default: true
        },
        enable_fetch_speed_mode: {
            type: 'boolean',
            title: 'Enable Fetch Speed Mode',
            default: true
        },
        remove_adult_content: {
            type: 'boolean',
            title: 'Remove Adult Content',
            default: true
        }
    },
    type: 'object',
    title: 'OptionsConfig',
    description: 'Configuration for various options.'
} as const;

export const OrionoidConfigSchema = {
    properties: {
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            default: false
        },
        api_key: {
            type: 'string',
            title: 'Api Key',
            default: ''
        },
        cached_results_only: {
            type: 'boolean',
            title: 'Cached Results Only',
            default: false
        },
        parameters: {
            additionalProperties: true,
            type: 'object',
            title: 'Parameters',
            default: {
                video3d: 'false',
                videoquality: 'sd_hd8k',
                limitcount: 5
            }
        },
        timeout: {
            type: 'integer',
            title: 'Timeout',
            default: 30
        },
        ratelimit: {
            type: 'boolean',
            title: 'Ratelimit',
            default: true,
            deprecated: true
        }
    },
    type: 'object',
    title: 'OrionoidConfig'
} as const;

export const OverseerrModelSchema = {
    properties: {
        update_interval: {
            type: 'integer',
            title: 'Update Interval',
            default: 60
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            default: false
        },
        url: {
            type: 'string',
            title: 'Url',
            default: 'http://localhost:5055'
        },
        api_key: {
            type: 'string',
            title: 'Api Key',
            default: ''
        },
        use_webhook: {
            type: 'boolean',
            title: 'Use Webhook',
            default: false
        }
    },
    type: 'object',
    title: 'OverseerrModel'
} as const;

export const ParseTorrentTitleResponseSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        },
        data: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['message', 'data'],
    title: 'ParseTorrentTitleResponse'
} as const;

export const ParsedDataSchema = {
    properties: {
        raw_title: {
            type: 'string',
            title: 'Raw Title'
        },
        parsed_title: {
            type: 'string',
            title: 'Parsed Title',
            default: ''
        },
        normalized_title: {
            type: 'string',
            title: 'Normalized Title',
            default: ''
        },
        trash: {
            type: 'boolean',
            title: 'Trash',
            default: false
        },
        adult: {
            type: 'boolean',
            title: 'Adult',
            default: false
        },
        year: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Year'
        },
        resolution: {
            type: 'string',
            title: 'Resolution',
            default: 'unknown'
        },
        seasons: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Seasons',
            default: []
        },
        episodes: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Episodes',
            default: []
        },
        complete: {
            type: 'boolean',
            title: 'Complete',
            default: false
        },
        volumes: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Volumes',
            default: []
        },
        languages: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Languages',
            default: []
        },
        quality: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Quality'
        },
        hdr: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Hdr',
            default: []
        },
        codec: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Codec'
        },
        audio: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Audio',
            default: []
        },
        channels: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Channels',
            default: []
        },
        dubbed: {
            type: 'boolean',
            title: 'Dubbed',
            default: false
        },
        subbed: {
            type: 'boolean',
            title: 'Subbed',
            default: false
        },
        date: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date'
        },
        group: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Group'
        },
        edition: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Edition'
        },
        bit_depth: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bit Depth'
        },
        bitrate: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bitrate'
        },
        network: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Network'
        },
        extended: {
            type: 'boolean',
            title: 'Extended',
            default: false
        },
        converted: {
            type: 'boolean',
            title: 'Converted',
            default: false
        },
        hardcoded: {
            type: 'boolean',
            title: 'Hardcoded',
            default: false
        },
        region: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Region'
        },
        ppv: {
            type: 'boolean',
            title: 'Ppv',
            default: false
        },
        site: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Site'
        },
        size: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Size'
        },
        proper: {
            type: 'boolean',
            title: 'Proper',
            default: false
        },
        repack: {
            type: 'boolean',
            title: 'Repack',
            default: false
        },
        retail: {
            type: 'boolean',
            title: 'Retail',
            default: false
        },
        upscaled: {
            type: 'boolean',
            title: 'Upscaled',
            default: false
        },
        remastered: {
            type: 'boolean',
            title: 'Remastered',
            default: false
        },
        unrated: {
            type: 'boolean',
            title: 'Unrated',
            default: false
        },
        documentary: {
            type: 'boolean',
            title: 'Documentary',
            default: false
        },
        episode_code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Episode Code'
        },
        country: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country'
        },
        container: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Container'
        },
        extension: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Extension'
        },
        extras: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Extras',
            default: []
        },
        torrent: {
            type: 'boolean',
            title: 'Torrent',
            default: false
        },
        scene: {
            type: 'boolean',
            title: 'Scene',
            default: false
        }
    },
    type: 'object',
    required: ['raw_title'],
    title: 'ParsedData',
    description: 'Parsed data model for a torrent title.'
} as const;

export const PauseResponseSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        },
        ids: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Ids'
        }
    },
    type: 'object',
    required: ['message', 'ids'],
    title: 'PauseResponse'
} as const;

export const PlexLibraryModelSchema = {
    properties: {
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            default: false
        },
        token: {
            type: 'string',
            title: 'Token',
            default: ''
        },
        url: {
            type: 'string',
            title: 'Url',
            default: 'http://localhost:32400'
        }
    },
    type: 'object',
    title: 'PlexLibraryModel'
} as const;

export const PlexWatchlistModelSchema = {
    properties: {
        update_interval: {
            type: 'integer',
            title: 'Update Interval',
            default: 60
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            default: false
        },
        rss: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Rss',
            default: []
        }
    },
    type: 'object',
    title: 'PlexWatchlistModel'
} as const;

export const PostProcessingSchema = {
    properties: {
        subliminal: {
            '$ref': '#/components/schemas/SubliminalConfig',
            default: {
                enabled: false,
                languages: ['eng'],
                providers: {
                    opensubtitles: {
                        enabled: false,
                        password: '',
                        username: ''
                    },
                    opensubtitlescom: {
                        enabled: false,
                        password: '',
                        username: ''
                    }
                }
            }
        }
    },
    type: 'object',
    title: 'PostProcessing'
} as const;

export const ProwlarrConfigSchema = {
    properties: {
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            default: false
        },
        url: {
            type: 'string',
            title: 'Url',
            default: 'http://localhost:9696'
        },
        api_key: {
            type: 'string',
            title: 'Api Key',
            default: ''
        },
        timeout: {
            type: 'integer',
            title: 'Timeout',
            default: 30
        },
        ratelimit: {
            type: 'boolean',
            title: 'Ratelimit',
            default: true
        },
        limiter_seconds: {
            type: 'integer',
            title: 'Limiter Seconds',
            default: 60
        }
    },
    type: 'object',
    title: 'ProwlarrConfig'
} as const;

export const QualityRankModelSchema = {
    properties: {
        av1: {
            '$ref': '#/components/schemas/CustomRank'
        },
        avc: {
            '$ref': '#/components/schemas/CustomRank'
        },
        bluray: {
            '$ref': '#/components/schemas/CustomRank'
        },
        dvd: {
            '$ref': '#/components/schemas/CustomRank'
        },
        hdtv: {
            '$ref': '#/components/schemas/CustomRank'
        },
        hevc: {
            '$ref': '#/components/schemas/CustomRank'
        },
        mpeg: {
            '$ref': '#/components/schemas/CustomRank'
        },
        remux: {
            '$ref': '#/components/schemas/CustomRank'
        },
        vhs: {
            '$ref': '#/components/schemas/CustomRank'
        },
        web: {
            '$ref': '#/components/schemas/CustomRank'
        },
        webdl: {
            '$ref': '#/components/schemas/CustomRank'
        },
        webmux: {
            '$ref': '#/components/schemas/CustomRank'
        },
        xvid: {
            '$ref': '#/components/schemas/CustomRank'
        }
    },
    type: 'object',
    title: 'QualityRankModel',
    description: 'Ranking configuration for quality attributes.'
} as const;

export const RDUserSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        points: {
            type: 'integer',
            title: 'Points',
            description: "User's RD points"
        },
        locale: {
            type: 'string',
            title: 'Locale'
        },
        avatar: {
            type: 'string',
            title: 'Avatar',
            description: "URL to the user's avatar"
        },
        type: {
            type: 'string',
            enum: ['free', 'premium'],
            title: 'Type'
        },
        premium: {
            type: 'integer',
            title: 'Premium',
            description: 'Premium subscription left in seconds'
        }
    },
    type: 'object',
    required: ['id', 'username', 'email', 'points', 'locale', 'avatar', 'type', 'premium'],
    title: 'RDUser'
} as const;

export const RTNSettingsModelSchema = {
    properties: {
        profile: {
            type: 'string',
            title: 'Profile',
            description: 'Identifier for the settings profile',
            default: 'default'
        },
        require: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Require',
            description: 'Patterns torrents must match to be considered'
        },
        exclude: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Exclude',
            description: 'Patterns that, if matched, result in torrent exclusion'
        },
        preferred: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Preferred',
            description: 'Patterns indicating preferred attributes in torrents'
        },
        resolutions: {
            '$ref': '#/components/schemas/ResolutionConfig',
            description: 'Configuration for enabled resolutions'
        },
        options: {
            '$ref': '#/components/schemas/OptionsConfig',
            description: 'General options for torrent filtering and ranking'
        },
        languages: {
            '$ref': '#/components/schemas/LanguagesConfig',
            description: 'Language preferences and restrictions'
        },
        custom_ranks: {
            '$ref': '#/components/schemas/CustomRanksConfig',
            description: 'Custom ranking configurations for specific attributes'
        }
    },
    type: 'object',
    title: 'RTNSettingsModel'
} as const;

export const RealDebridModelSchema = {
    properties: {
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            default: false
        },
        api_key: {
            type: 'string',
            title: 'Api Key',
            default: ''
        }
    },
    type: 'object',
    title: 'RealDebridModel'
} as const;

export const RemoveResponseSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        },
        ids: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Ids'
        }
    },
    type: 'object',
    required: ['message', 'ids'],
    title: 'RemoveResponse'
} as const;

export const RepairSymlinksResponseSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'RepairSymlinksResponse'
} as const;

export const ResetResponseSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        },
        ids: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Ids'
        }
    },
    type: 'object',
    required: ['message', 'ids'],
    title: 'ResetResponse'
} as const;

export const ResolutionConfigSchema = {
    properties: {
        r2160p: {
            type: 'boolean',
            title: 'R2160P',
            default: false
        },
        r1080p: {
            type: 'boolean',
            title: 'R1080P',
            default: true
        },
        r720p: {
            type: 'boolean',
            title: 'R720P',
            default: true
        },
        r480p: {
            type: 'boolean',
            title: 'R480P',
            default: false
        },
        r360p: {
            type: 'boolean',
            title: 'R360P',
            default: false
        },
        unknown: {
            type: 'boolean',
            title: 'Unknown',
            default: true
        }
    },
    type: 'object',
    title: 'ResolutionConfig',
    description: 'Configuration for which resolutions are enabled.'
} as const;

export const RetryResponseSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        },
        ids: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Ids'
        }
    },
    type: 'object',
    required: ['message', 'ids'],
    title: 'RetryResponse'
} as const;

export const RipsRankModelSchema = {
    properties: {
        bdrip: {
            '$ref': '#/components/schemas/CustomRank'
        },
        brrip: {
            '$ref': '#/components/schemas/CustomRank'
        },
        dvdrip: {
            '$ref': '#/components/schemas/CustomRank'
        },
        hdrip: {
            '$ref': '#/components/schemas/CustomRank'
        },
        ppvrip: {
            '$ref': '#/components/schemas/CustomRank'
        },
        satrip: {
            '$ref': '#/components/schemas/CustomRank'
        },
        tvrip: {
            '$ref': '#/components/schemas/CustomRank'
        },
        uhdrip: {
            '$ref': '#/components/schemas/CustomRank'
        },
        vhsrip: {
            '$ref': '#/components/schemas/CustomRank'
        },
        webdlrip: {
            '$ref': '#/components/schemas/CustomRank'
        },
        webrip: {
            '$ref': '#/components/schemas/CustomRank'
        }
    },
    type: 'object',
    title: 'RipsRankModel',
    description: 'Ranking configuration for rips attributes.'
} as const;

export const RootResponseSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        },
        version: {
            type: 'string',
            title: 'Version'
        }
    },
    type: 'object',
    required: ['message', 'version'],
    title: 'RootResponse'
} as const;

export const ScrapeItemResponseSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        },
        streams: {
            additionalProperties: {
                '$ref': '#/components/schemas/Stream'
            },
            type: 'object',
            title: 'Streams'
        }
    },
    type: 'object',
    required: ['message', 'streams'],
    title: 'ScrapeItemResponse'
} as const;

export const ScraperModelSchema = {
    properties: {
        after_2: {
            type: 'number',
            title: 'After 2',
            default: 2
        },
        after_5: {
            type: 'number',
            title: 'After 5',
            default: 6
        },
        after_10: {
            type: 'number',
            title: 'After 10',
            default: 24
        },
        parse_debug: {
            type: 'boolean',
            title: 'Parse Debug',
            default: false
        },
        enable_aliases: {
            type: 'boolean',
            title: 'Enable Aliases',
            default: true
        },
        bucket_limit: {
            type: 'integer',
            maximum: 20,
            minimum: 0,
            title: 'Bucket Limit',
            default: 5
        },
        max_failed_attempts: {
            type: 'integer',
            maximum: 10,
            minimum: 0,
            title: 'Max Failed Attempts',
            default: 0
        },
        dubbed_anime_only: {
            type: 'boolean',
            title: 'Dubbed Anime Only',
            default: false
        },
        torrentio: {
            '$ref': '#/components/schemas/TorrentioConfig',
            default: {
                enabled: false,
                filter: 'sort=qualitysize%7Cqualityfilter=480p,scr,cam',
                url: 'http://torrentio.strem.fun',
                timeout: 30,
                ratelimit: true,
                proxy_url: ''
            }
        },
        knightcrawler: {
            '$ref': '#/components/schemas/KnightcrawlerConfig',
            default: {
                enabled: false,
                filter: 'sort=qualitysize%7Cqualityfilter=480p,scr,cam',
                url: 'https://knightcrawler.elfhosted.com',
                timeout: 30,
                ratelimit: true
            }
        },
        jackett: {
            '$ref': '#/components/schemas/JackettConfig',
            default: {
                enabled: false,
                url: 'http://localhost:9117',
                api_key: '',
                timeout: 30,
                ratelimit: true
            }
        },
        prowlarr: {
            '$ref': '#/components/schemas/ProwlarrConfig',
            default: {
                enabled: false,
                url: 'http://localhost:9696',
                api_key: '',
                timeout: 30,
                ratelimit: true,
                limiter_seconds: 60
            }
        },
        orionoid: {
            '$ref': '#/components/schemas/OrionoidConfig',
            default: {
                enabled: false,
                api_key: '',
                cached_results_only: false,
                parameters: {
                    limitcount: 5,
                    video3d: 'false',
                    videoquality: 'sd_hd8k'
                },
                timeout: 30,
                ratelimit: true
            }
        },
        mediafusion: {
            '$ref': '#/components/schemas/MediafusionConfig',
            default: {
                enabled: false,
                url: 'https://mediafusion.elfhosted.com',
                timeout: 30,
                ratelimit: true
            }
        },
        zilean: {
            '$ref': '#/components/schemas/ZileanConfig',
            default: {
                enabled: false,
                url: 'http://localhost:8181',
                timeout: 30,
                ratelimit: true
            }
        },
        comet: {
            '$ref': '#/components/schemas/CometConfig',
            default: {
                enabled: false,
                url: 'https://comet.elfhosted.com',
                timeout: 30,
                ratelimit: true
            }
        }
    },
    type: 'object',
    title: 'ScraperModel'
} as const;

export const SelectFilesResponseSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        },
        download_type: {
            type: 'string',
            enum: ['cached', 'uncached'],
            title: 'Download Type'
        }
    },
    type: 'object',
    required: ['message', 'download_type'],
    title: 'SelectFilesResponse'
} as const;

export const SessionResponseSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'SessionResponse'
} as const;

export const SetSettingsSchema = {
    properties: {
        key: {
            type: 'string',
            title: 'Key'
        },
        value: {
            title: 'Value'
        }
    },
    type: 'object',
    required: ['key', 'value'],
    title: 'SetSettings'
} as const;

export const ShowFileDataSchema = {
    additionalProperties: {
        additionalProperties: {
            '$ref': '#/components/schemas/DebridFile'
        },
        type: 'object'
    },
    type: 'object',
    title: 'ShowFileData',
    description: `Root model for show file data that maps seasons to episodes to file data.

Example:
{
    1: {  # Season 1
        1: {"filename": "path/to/s01e01.mkv"},  # Episode 1
        2: {"filename": "path/to/s01e02.mkv"}   # Episode 2
    },
    2: {  # Season 2
        1: {"filename": "path/to/s02e01.mkv"}   # Episode 1
    }
}`
} as const;

export const StartSessionResponseSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        },
        session_id: {
            type: 'string',
            title: 'Session Id'
        },
        torrent_id: {
            type: 'string',
            title: 'Torrent Id'
        },
        torrent_info: {
            '$ref': '#/components/schemas/TorrentInfo'
        },
        containers: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/TorrentContainer'
                },
                {
                    type: 'null'
                }
            ]
        },
        expires_at: {
            type: 'string',
            title: 'Expires At'
        }
    },
    type: 'object',
    required: ['message', 'session_id', 'torrent_id', 'torrent_info', 'containers', 'expires_at'],
    title: 'StartSessionResponse'
} as const;

export const StateResponseSchema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        states: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'States'
        }
    },
    type: 'object',
    required: ['success', 'states'],
    title: 'StateResponse'
} as const;

export const StatesSchema = {
    type: 'string',
    enum: ['Unknown', 'Unreleased', 'Ongoing', 'Requested', 'Indexed', 'Scraped', 'Downloaded', 'Symlinked', 'Completed', 'PartiallyCompleted', 'Failed', 'Paused'],
    title: 'States'
} as const;

export const StatsResponseSchema = {
    properties: {
        total_items: {
            type: 'integer',
            title: 'Total Items'
        },
        total_movies: {
            type: 'integer',
            title: 'Total Movies'
        },
        total_shows: {
            type: 'integer',
            title: 'Total Shows'
        },
        total_seasons: {
            type: 'integer',
            title: 'Total Seasons'
        },
        total_episodes: {
            type: 'integer',
            title: 'Total Episodes'
        },
        total_symlinks: {
            type: 'integer',
            title: 'Total Symlinks'
        },
        incomplete_items: {
            type: 'integer',
            title: 'Incomplete Items'
        },
        incomplete_retries: {
            additionalProperties: {
                type: 'integer'
            },
            type: 'object',
            title: 'Incomplete Retries',
            description: 'Media item log string: number of retries'
        },
        states: {
            additionalProperties: {
                type: 'integer'
            },
            propertyNames: {
                '$ref': '#/components/schemas/States'
            },
            type: 'object',
            title: 'States'
        }
    },
    type: 'object',
    required: ['total_items', 'total_movies', 'total_shows', 'total_seasons', 'total_episodes', 'total_symlinks', 'incomplete_items', 'incomplete_retries', 'states'],
    title: 'StatsResponse'
} as const;

export const StreamSchema = {
    properties: {
        infohash: {
            type: 'string',
            title: 'Infohash'
        },
        raw_title: {
            type: 'string',
            title: 'Raw Title'
        },
        parsed_title: {
            type: 'string',
            title: 'Parsed Title'
        },
        parsed_data: {
            '$ref': '#/components/schemas/ParsedData'
        },
        rank: {
            type: 'integer',
            title: 'Rank'
        },
        lev_ratio: {
            type: 'number',
            title: 'Lev Ratio'
        },
        is_cached: {
            type: 'boolean',
            title: 'Is Cached',
            default: false
        }
    },
    type: 'object',
    required: ['infohash', 'raw_title', 'parsed_title', 'parsed_data', 'rank', 'lev_ratio'],
    title: 'Stream'
} as const;

export const SubliminalConfigSchema = {
    properties: {
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            default: false
        },
        languages: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Languages',
            default: ['eng']
        },
        providers: {
            additionalProperties: true,
            type: 'object',
            title: 'Providers',
            default: {
                opensubtitles: {
                    enabled: false,
                    password: '',
                    username: ''
                },
                opensubtitlescom: {
                    enabled: false,
                    password: '',
                    username: ''
                }
            }
        }
    },
    type: 'object',
    title: 'SubliminalConfig'
} as const;

export const SymlinkModelSchema = {
    properties: {
        rclone_path: {
            type: 'string',
            format: 'path',
            title: 'Rclone Path',
            default: '.'
        },
        library_path: {
            type: 'string',
            format: 'path',
            title: 'Library Path',
            default: '.'
        },
        separate_anime_dirs: {
            type: 'boolean',
            title: 'Separate Anime Dirs',
            default: false
        },
        repair_symlinks: {
            type: 'boolean',
            title: 'Repair Symlinks',
            default: false
        },
        repair_interval: {
            type: 'number',
            title: 'Repair Interval',
            default: 6
        }
    },
    type: 'object',
    title: 'SymlinkModel'
} as const;

export const TorrentContainerSchema = {
    properties: {
        infohash: {
            type: 'string',
            title: 'Infohash'
        },
        files: {
            items: {
                '$ref': '#/components/schemas/DebridFile'
            },
            type: 'array',
            title: 'Files'
        }
    },
    type: 'object',
    required: ['infohash'],
    title: 'TorrentContainer',
    description: 'Represents a collection of files from an infohash from a debrid service'
} as const;

export const TorrentInfoSchema = {
    properties: {
        id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'string'
                }
            ],
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        status: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Status'
        },
        infohash: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Infohash'
        },
        progress: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Progress'
        },
        bytes: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bytes'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        expires_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expires At'
        },
        completed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completed At'
        },
        alternative_filename: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Alternative Filename'
        },
        files: {
            additionalProperties: {
                additionalProperties: {
                    anyOf: [
                        {
                            type: 'integer'
                        },
                        {
                            type: 'string'
                        }
                    ]
                },
                type: 'object'
            },
            type: 'object',
            title: 'Files'
        }
    },
    type: 'object',
    required: ['id', 'name'],
    title: 'TorrentInfo',
    description: 'Torrent information from a debrid service'
} as const;

export const TorrentioConfigSchema = {
    properties: {
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            default: false
        },
        filter: {
            type: 'string',
            title: 'Filter',
            default: 'sort=qualitysize%7Cqualityfilter=480p,scr,cam'
        },
        url: {
            type: 'string',
            title: 'Url',
            default: 'http://torrentio.strem.fun'
        },
        timeout: {
            type: 'integer',
            title: 'Timeout',
            default: 30
        },
        ratelimit: {
            type: 'boolean',
            title: 'Ratelimit',
            default: true,
            deprecated: true
        },
        proxy_url: {
            type: 'string',
            title: 'Proxy Url',
            default: ''
        }
    },
    type: 'object',
    title: 'TorrentioConfig'
} as const;

export const TraktModelSchema = {
    properties: {
        update_interval: {
            type: 'integer',
            title: 'Update Interval',
            default: 86400
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            default: false
        },
        api_key: {
            type: 'string',
            title: 'Api Key',
            default: ''
        },
        watchlist: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Watchlist',
            default: []
        },
        user_lists: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'User Lists',
            default: []
        },
        collection: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Collection',
            default: []
        },
        fetch_trending: {
            type: 'boolean',
            title: 'Fetch Trending',
            default: false
        },
        trending_count: {
            type: 'integer',
            title: 'Trending Count',
            default: 10
        },
        fetch_popular: {
            type: 'boolean',
            title: 'Fetch Popular',
            default: false
        },
        popular_count: {
            type: 'integer',
            title: 'Popular Count',
            default: 10
        },
        fetch_most_watched: {
            type: 'boolean',
            title: 'Fetch Most Watched',
            default: false
        },
        most_watched_period: {
            type: 'string',
            title: 'Most Watched Period',
            default: 'weekly'
        },
        most_watched_count: {
            type: 'integer',
            title: 'Most Watched Count',
            default: 10
        },
        oauth: {
            '$ref': '#/components/schemas/TraktOauthModel',
            default: {
                oauth_client_id: '',
                oauth_client_secret: '',
                oauth_redirect_uri: '',
                access_token: '',
                refresh_token: ''
            }
        }
    },
    type: 'object',
    title: 'TraktModel'
} as const;

export const TraktOAuthInitiateResponseSchema = {
    properties: {
        auth_url: {
            type: 'string',
            title: 'Auth Url'
        }
    },
    type: 'object',
    required: ['auth_url'],
    title: 'TraktOAuthInitiateResponse'
} as const;

export const TraktOauthModelSchema = {
    properties: {
        oauth_client_id: {
            type: 'string',
            title: 'Oauth Client Id',
            default: ''
        },
        oauth_client_secret: {
            type: 'string',
            title: 'Oauth Client Secret',
            default: ''
        },
        oauth_redirect_uri: {
            type: 'string',
            title: 'Oauth Redirect Uri',
            default: ''
        },
        access_token: {
            type: 'string',
            title: 'Access Token',
            default: ''
        },
        refresh_token: {
            type: 'string',
            title: 'Refresh Token',
            default: ''
        }
    },
    type: 'object',
    title: 'TraktOauthModel'
} as const;

export const TrashRankModelSchema = {
    properties: {
        cam: {
            '$ref': '#/components/schemas/CustomRank'
        },
        clean_audio: {
            '$ref': '#/components/schemas/CustomRank'
        },
        pdtv: {
            '$ref': '#/components/schemas/CustomRank'
        },
        r5: {
            '$ref': '#/components/schemas/CustomRank'
        },
        screener: {
            '$ref': '#/components/schemas/CustomRank'
        },
        size: {
            '$ref': '#/components/schemas/CustomRank'
        },
        telecine: {
            '$ref': '#/components/schemas/CustomRank'
        },
        telesync: {
            '$ref': '#/components/schemas/CustomRank'
        }
    },
    type: 'object',
    title: 'TrashRankModel',
    description: 'Ranking configuration for trash attributes.'
} as const;

export const UpdateAttributesResponseSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'UpdateAttributesResponse'
} as const;

export const UpdateOngoingResponseSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        },
        updated_items: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Updated Items'
        }
    },
    type: 'object',
    required: ['message', 'updated_items'],
    title: 'UpdateOngoingResponse'
} as const;

export const UpdatersModelSchema = {
    properties: {
        updater_interval: {
            type: 'integer',
            title: 'Updater Interval',
            default: 120
        },
        plex: {
            '$ref': '#/components/schemas/PlexLibraryModel',
            default: {
                enabled: false,
                token: '',
                url: 'http://localhost:32400'
            }
        },
        jellyfin: {
            '$ref': '#/components/schemas/JellyfinLibraryModel',
            default: {
                enabled: false,
                api_key: '',
                url: 'http://localhost:8096'
            }
        },
        emby: {
            '$ref': '#/components/schemas/EmbyLibraryModel',
            default: {
                enabled: false,
                api_key: '',
                url: 'http://localhost:8096'
            }
        }
    },
    type: 'object',
    title: 'UpdatersModel'
} as const;

export const UploadLogsResponseSchema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        url: {
            type: 'string',
            maxLength: 2083,
            minLength: 1,
            format: 'uri',
            title: 'Url',
            description: 'URL to the uploaded log file. 50M Filesize limit. 180 day retention.'
        }
    },
    type: 'object',
    required: ['success', 'url'],
    title: 'UploadLogsResponse'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const ZileanConfigSchema = {
    properties: {
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            default: false
        },
        url: {
            type: 'string',
            title: 'Url',
            default: 'http://localhost:8181'
        },
        timeout: {
            type: 'integer',
            title: 'Timeout',
            default: 30
        },
        ratelimit: {
            type: 'boolean',
            title: 'Ratelimit',
            default: true,
            deprecated: true
        }
    },
    type: 'object',
    title: 'ZileanConfig'
} as const;

export const routers__secure__default__EventResponseSchema = {
    properties: {
        events: {
            additionalProperties: {
                items: {
                    type: 'string'
                },
                type: 'array'
            },
            type: 'object',
            title: 'Events'
        }
    },
    type: 'object',
    required: ['events'],
    title: 'EventResponse'
} as const;

export const routers__secure__stream__EventResponseSchema = {
    properties: {
        data: {
            additionalProperties: true,
            type: 'object',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'EventResponse'
} as const;