name: Release Please

on:
    push:
        branches:
            - main

permissions:
    contents: write
    pull-requests: write

concurrency:
    group: release-${{ github.ref }}
    cancel-in-progress: true

jobs:
    release-please:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - uses: googleapis/release-please-action@v4.4.0
              id: release
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
